kordan/moodle-mod_surveypro

- classes/itembase.class.php
- classes/templatebase.class.php
- documentation.txt
- field/age/classes/plugin.class.php
- field/date/classes/plugin.class.php
- field/datetime/classes/plugin.class.php
- field/integer/classes/plugin.class.php
- locallib.php
- tests/behat/duplicate.feature
Behat tests are still running but each executed test passed regularly. So I believe the correction is working fine.
As before, the only failing test is duplicate.feature. Well... it is not completely failing. Mac terminal simply describe it with a "-" (minus) instead of the usual "." (dot) but, actually no "F" appear in the terminal feedback.
Some very silly detail has been changed to let the code simpler to read.
> NOBUG mod_surveypro: fixed issue in get_item when $itemseed is not set

- layout_manage.php
- layout_preview.php
- layout_validation.php
- lib.php
- mtemplates_apply.php
- mtemplates_create.php
- report/attachments_overview/uploads.php
- report/attachments_overview/view.php
- report/colles/view.php
- report/count/view.php
- report/frequency/view.php
- report/missing/view.php
- report/submitting/view.php
- utemplates_apply.php
- utemplates_create.php
- utemplates_import.php
- utemplates_manage.php
- view_cover.php
- view_form.php
- view_search.php
The line of code:
navigation_node::override_active_url($url);
used in almost each landing page of the module
is useless.
> CONTRIB-6197 mod_surveypro: removed override_active_url

- .travis.yml
I get rid of the php 5.5 and php 5.6 (keeping only 5.4 and 7.0, aka, min and max php versions supported) and I add the master branch, so I always know if there is some change in master that requires my attention in the module.
> CONTRIB-6204 mod_surveypro: changed .travis.yml

- classes/formbase.class.php
- classes/itembase.class.php
- classes/itemlist.class.php
- classes/utils.class.php
- classes/view_cover.class.php
- classes/view_form.class.php
- classes/view_import.class.php
- classes/view_submissions.class.php
- form/outform/fill_form.php
- form/outform/search_form.php
- layout_itemsetup.php
- layout_manage.php
- lib.php
- locallib.php
- mtemplates_apply.php
- report/attachments_overview/form/filter_form.php
- utemplates_apply.php
During  code cleanup I found that
- surveypro_fetch_items_seeds was more complex than needed
- item_validate_variablename was more complex than needed too
and
- get_used_plugin_list was written three times in the code.
item_validate_variablename had also an error (with very low probability to occur, but my Editing Teacher are really nice :o) )
Yes, they should be three PR but they are all small changes.
I apologise in advance.
> CONTRIB-6213 mod_surveypro: make code simpler

- tests/behat/behat_mod_surveypro.php
- tests/behat/multilang_mastertemplate.feature
Depending of browser language it may be possible for some tests
to be passing in some sites but not in others.
So I've created a new step:
And I follow "languagename" in the language menu
In order to, always, ensure the desired language is being used.
That way, the teacher user sees everything in English and the student
user sees everything in Italian.
It's passing here now, and hope travis also will. For your consideration. Maybe you can try it in your Italian laptop....
Ciao :-)
PS: Note I don't really understand why it was passing for you, specially why the teacher had the Italian "login" when the survey is in English. Rare, rare. Anyway, now we explicitly set the desired language so mysteries are history.
> NOBUG: Fix multilanguage test to ensure UI is in the expected lang.

- tests/behat/backup_restore.feature
Now it will work in any database irrespectively of the colllation used.
I always use here "case-sensitive" collations... and bet travis also does, hence the 2 strings were not matching. Now It should work ok everywhere.
> NOBUG: Fix case-sensitiveness potential problem

- field/checkbox/classes/mform_advcheckbox.php
- field/checkbox/classes/mform_checkbox.php
- field/fileupload/classes/mform_filemanager.php
- field/radiobutton/classes/mform_radio.php
- field/select/classes/mform_select.php
- field/textarea/classes/mform_editor.php
- format/label/classes/mform_static.php
As far as I understand, 
there was a deeeeeep error but, in spite of this, it never come out.
It is in surveypro/field/checkbox/classes/mform_advcheckbox.php
where I had:
public function __construct($elementName=null, $elementLabel=null, $attributes=null, $options=null) {
parent::__construct($elementName, $elementLabel, $attributes, $options);
}
while the parent class had
public function __construct($elementName=null, $elementLabel=null, $text=null, $attributes=null, $options=null)
I simply added $text=null to my constructor and to the call to the parent constructor and all still works fine.
I made a quick test and all seems to be fine.
Next week I will investigate more.
> NOBUG mod_surveypro: preserve from codechecker and minor phpdoc fix

- classes/itemlist.class.php
- layout_itemsetup.php
- layout_manage.php
- layout_validation.php
it strongly seems that the property saveasnew of the mod_surveypro_itemlist class 
is 100% useless and never used.
I removed it and now I push the patch to verify the opinion of travis-ci.
> CONTRIB-6230 mod_surveypro: deleted saveasnew propery

- classes/itembase.class.php
- field/age/classes/plugin.class.php
- field/autofill/classes/plugin.class.php
- field/boolean/classes/plugin.class.php
- field/character/classes/plugin.class.php
- field/checkbox/classes/plugin.class.php
- field/date/classes/plugin.class.php
- field/datetime/classes/plugin.class.php
- field/fileupload/classes/plugin.class.php
- field/integer/classes/plugin.class.php
- field/multiselect/classes/plugin.class.php
- field/numeric/classes/plugin.class.php
- field/radiobutton/classes/plugin.class.php
- field/rate/classes/plugin.class.php
- field/recurrence/classes/plugin.class.php
- field/select/classes/plugin.class.php
- field/shortdate/classes/plugin.class.php
- field/textarea/classes/plugin.class.php
- field/time/classes/plugin.class.php
- form/outform/fill_form.php
- form/outform/search_form.php
- format/fieldset/classes/plugin.class.php
- format/fieldsetend/classes/plugin.class.php
- format/label/classes/plugin.class.php
- format/pagebreak/classes/plugin.class.php
userform_mform_validation is the method of each item plugin
used to validate the mform element of the form that the student will fill and submit.
It gets as input a totally useless $surveypro because $surveypro is already a class property.
In the frame of this patch I also replaced EACH occurrence of $surveypro (in plugin.class.php) with $this->surveypro as this property is always defined by the parent constructor.
> CONTRIB-6259 surveypro: del. $surveypro from userform_mform_validation

- classes/itembase.class.php
- field/age/classes/plugin.class.php
- field/autofill/classes/plugin.class.php
- field/boolean/classes/plugin.class.php
- field/character/classes/plugin.class.php
- field/checkbox/classes/plugin.class.php
- field/date/classes/plugin.class.php
- field/datetime/classes/plugin.class.php
- field/fileupload/classes/plugin.class.php
- field/integer/classes/plugin.class.php
- field/multiselect/classes/plugin.class.php
- field/numeric/classes/plugin.class.php
- field/radiobutton/classes/plugin.class.php
- field/rate/classes/plugin.class.php
- field/recurrence/classes/plugin.class.php
- field/select/classes/plugin.class.php
- field/shortdate/classes/plugin.class.php
- field/textarea/classes/plugin.class.php
- field/time/classes/plugin.class.php
- format/fieldset/classes/plugin.class.php
- format/fieldsetend/classes/plugin.class.php
- format/label/classes/plugin.class.php
- format/pagebreak/classes/plugin.class.php
- locallib.php
Really silly code clean to fulfill:
Avoid excessively long variable names like $evaluateparentcontent. Keep variable name length under 20.
> NOBUG mod_surveypro: silly code clean

- classes/view_submissions.class.php
Not much to say, just it seems to be the unique remaining phpcs error in the module, heading to get it passing (apart from warnings).
> NOBUG: Delete phpcs remaining error (2 blank lines)

- tests/behat/overwrite_mastertemplate.feature
- tests/behat/preserve_autofillpersonaldata.feature
Since the branch better_userform_mform_element the scenario: "test that editing a submission, autofill userID is not overwritten" no longer works fine because the autofill item element has been changed from static text to regular text input field.
This branch let work fine again that behat test.
> CONTRIB-6269 mod_surveypro: fixed failing behat test

- classes/formbase.class.php
- field/age/classes/plugin.class.php
- field/autofill/classes/plugin.class.php
- field/boolean/classes/plugin.class.php
- field/character/classes/plugin.class.php
- field/checkbox/classes/plugin.class.php
- field/date/classes/plugin.class.php
- field/datetime/classes/plugin.class.php
- field/fileupload/classes/plugin.class.php
- field/integer/classes/plugin.class.php
- field/multiselect/classes/plugin.class.php
- field/numeric/classes/plugin.class.php
- field/radiobutton/classes/plugin.class.php
- field/rate/classes/plugin.class.php
- field/recurrence/classes/plugin.class.php
- field/select/classes/plugin.class.php
- field/shortdate/classes/plugin.class.php
- field/textarea/classes/plugin.class.php
- field/time/classes/plugin.class.php
- form/outform/fill_form.php
- format/label/classes/plugin.class.php
- styles.css
With that addition I am able to apply a style to all the elements specifying plugin and item detail. For instance: date_select selects the three drop down menu with day, month and year or date_chack selects the noanswer checkbox of each date item.
This is specially useful for the autofill plugin that is changed in its aspect to look like a static text.
> CONTRIB-6268 mod_surveypro: added static styles per each item

- .travis.yml
We do postgres and mysql tests both in lates stable (31) and master.
And only one of them in older stables (30)
> NOBUG: Update travis so tests are performed against new 31_STABLE

- classes/itemlist.class.php
- classes/utemplate.class.php
- lang/en/surveypro.php
Almost each action in surveypro lies over two steps: 
1) ask for confirmation
2) feedback.
Usertemplate deletion is still missing the feedback when the action is confirmed.
> CONTRIB-6286 mod_surveypro: added a feedback to utempalte deletion

- classes/itembase.php
- classes/mastertemplate.php
- templatemaster/classes/class.php
- templatemaster/lang/en/surveyprotemplate_pluginname.php
- templatemaster/template.xml
- templatemaster/version.php
In this patch I tried to fix these issues:
- master template still accepts numbers in the name
- the name of its class is wrong in <<mastertemplatename>>/classes/class.php
- there is no test about the correctness of the module "templatemaster" folder
- the temp folder, where the zip file is created, has not an extra security clean so, if the master template process crashes, the undeleted temporary folder will cause a new crash each time a new mastertemplate is asked with the same name.
> Mtemplate save improvements

- classes/itembase.php
- field/age/classes/field.php
- field/boolean/classes/field.php
- field/character/classes/field.php
- field/checkbox/classes/field.php
- field/date/classes/field.php
- field/datetime/classes/field.php
- field/fileupload/classes/field.php
- field/integer/classes/field.php
- field/multiselect/classes/field.php
- field/numeric/classes/field.php
- field/radiobutton/classes/field.php
- field/rate/classes/field.php
- field/recurrence/classes/field.php
- field/select/classes/field.php
- field/shortdate/classes/field.php
- field/time/classes/field.php
- report/frequency/classes/report.php
- report/frequency/graph.php
- report/frequency/lang/en/surveyproreport_frequency.php
- report/frequency/view.php
In the frequency report there was a misunderstanding between the count of submissions and the count of answers to the item id=xxx. Of course they may be different and this was leading to sum of percentages different from 1.
Second problem was that the string in the first column of the report table was not correct because the value "SURVEYPRO_ANSWERNOTINDBVALUE" was not managed in the public method userform_db_to_export($answer, $format='') of each field class.
> CONTRIB-6398 mod_surveypro: fixed bad frequency report

- classes/mastertemplate.php
At master template save time
the temporary folder can not be deleted because it is still not empty.
This was due to wrong list of provided filenames.
> CONTRIB-6406 mod_surveypro: fixed wrong list of filenames

- field/numeric/classes/field.php
Numeric input bounded by lowebbound or upperbound or both, never validate even if it is correct.
> CONTRIB-6409 mod_surveypro: typecast added to numbers

- report/frequency/classes/report.php
in the frequency report 
the distribution of answers has to display the friendly name of the answers.
For instance:
to the radio button element "Which protocol do you use to code diagnoses" with answers "DSM IV-TR", "ICD-9", "ICD-10"
I have to get a frequency report displaying:
DSM IV-TR.....3
ICD-9..............6
ICD-10............8
and not
0...............3
1...............6
2...............8
> NOBUG mod_surveypro: asked for friendly format to answers

- classes/view_form.php
- field/checkbox/classes/field.php
- field/checkbox/db/upgrade.php
Added explanation about the difference between $required and $minimumrequired and their compatibility for checkboxes elements.
This is needed because at first glace $minimumrequired greater than 0 may appear inappropriate for not required element.
The trick is in the semantic of the checkbox. In a word: students can never jump a checkbox element even if they leave the element untouched.
The added explanation describe exactly this.
> NOBUG mod_surveypro: added explanation of use

- classes/itemlist.php
In the layout_manage page, the list of items is no longer equipped with arrows to change the order of items.
The issue is due to the change from get_record to get_recordset to save memory.
> CONTRIB-6415 mod_surveypro: changed the way to count items

- lang/en/surveypro.php
removed the second definition of $string['hideallitems']
> NOBUG mod_surveypro: $string['hideallitems'] defined twice

- classes/submission.php
Students accessing a surveypro without elements are redirected to a page they can not access.
> CONTRIB-6421 mod_surveypro: forked the redirect

- field/recurrence/classes/field.php
At recurrence item creation the download format menu lists incorrect examples.
> CONTRIB-6426 mod_surveypro: fixed download format menu

- .travis.yml
- Moodle 3.2 and up will run PHP 5.6 and 7.0 (default envs).
- Moodle 3.0 and 3.1 will run PHP 5.4 and 7.0 (excluding PHP 5.6).
> NOBUG: re-organize combinations to cover PHP requirements.

- classes/itemlist.php
Sorting elements by custom number in relation table leads to a mysql error.
SELECT id as itemid, plugin, type FROM head_surveypro_item WHERE surveyproid = ? ORDER BY customnumber ASC, sortindex DESC
[array (
0 => '152',
)]
Error code: dmlreadexception
Stack trace:
line 474 of /lib/dml/moodle_database.php: dml_read_exception thrown
line 1027 of /lib/dml/mysqli_native_moodle_database.php: call to moodle_database->query_end()
line 1250 of /lib/dml/moodle_database.php: call to mysqli_native_moodle_database->get_recordset_sql()
line 1198 of /lib/dml/moodle_database.php: call to moodle_database->get_recordset_select()
line 705 of /mod/surveypro/classes/itemlist.php: call to moodle_database->get_recordset()
line 101 of /mod/surveypro/layout_validation.php: call to …
> CONTRIB-6449 mod_surveypro: denied sort by customnumber

- field/textarea/form/itemsetup_form.php
- form/items/itembase_form.php
- form/outform/fill_form.php
- form/outform/search_form.php
- report/frequency/form/item_form.php
I had no evidence at all of an error but I think the correct way to proceed is using
`$errors = parent::validation($data, $files);`
> NOBUG mod_surveypro: added correct $error definition

- classes/submission.php
- classes/view_form.php
- field/numeric/tests/behat/multiformat.feature
- view.php
- view_form.php
In the frame of this patch I found an undiscovered issue.
To submits a surveypro, students are redirected to the view_form page.
The view_form page verifies the submission, saves it and much more.
IF a submissions was really performed (no pause, no cancel, no previous page button was pressed) the thanks page is displayed, buttons to continue are displayed AND THE EXECUTION IS STOPPED.
This is very bad because if in that page the student switches the lang using the corresponding menu, he/she is redirected to the view_form page that is the one to submit one more response and not to the thanks page were he/she actually is.
> CONTRIB-6466 mod_surveypro: new test for numbers using different formats

- field/textarea/tests/behat/itemform.feature
I added one more verification to an existing test now that I learned how to do it.
I verify that the two textarea elements are really equipped with the editor (the first), editor free (the second).
> NOBUG mod_surveypro: one more check in textarea

- classes/submission.php
- report/attachments/classes/report.php
- report/attachments/form/filter_form.php
- report/attachments/uploads.php
- report/delayedusers/classes/report.php
- report/frequency/classes/report.php
- report/frequency/form/item_form.php
- report/frequency/view.php
- report/responsesperuser/classes/report.php
- report/userspercount/classes/report.php
Background.
Let's understand: submission === response.
At responses import time (from "moodle instance 1" to "moodle instance 2"),
the ownership of responses is assigned to the user with id == submission->userid.
It may happen that a submission has a userid not existing in "moodle instance 2".
In this case the ownership of the response is assigned to the user that is performing the import.
This user is not forced to be enrolled in the course so, at the end, it may happen that a submission in "moodle instance 2" is assigned to a not enrolled user.
This is the background.
The issue:
Usually the teacher don't want to see submissions from user not enrolled.
At the same time the admin WANTS to see its submissions even if he is not enrolled in the course.
So... which submission has to be …
> CONTRIB-6476 mod_surveypro: improved submissions selection

- classes/view_form.php
- lib.php
- report/colles/classes/report.php
There are still some occurrences of 
IN ('.implode(',', $xxx).')'
in the code that should be replaced by appropriate code.
I am not fixing the code into reports because I will fix them when I will add the group filter.
> CONTRIB-6482 mod_surveypro: replaced direct IN in sql

- classes/reportbase.php
- report/delayedusers/classes/report.php
- report/delayedusers/view.php
Currently, for courses divided into groups, the delayed user report allows to select:
- users from all groups
- users from a single group
- users non enrolled.
This last option IS A LOGICAL ERROR.
You can not ask for users...
"not in any group" (alias: "not enrolled") && "still not submitting" (delayed)
because guest user will ALWAYS be counted.
If a user is "not enrolled", of course he still didn't submit.
The "not in any group" item, in the "delayed user" report, IS A NONSENSE
it is needed when users...
ACTUALLY HAVE submissions EVEN IF they are not enrolled
but in this report only users WITHOUT submission are searched.
> CONTRIB-6492 mod_surveypro:changed logic search

- lib.php
- report/colles/classes/report.php
- template/collesactual/lang/en/surveyprotemplate_collesactual.php
- template/collesactual/lang/it/surveyprotemplate_collesactual.php
- template/collesactual/tests/behat/graphs.feature
- template/collesactualpreferred/lang/en/surveyprotemplate_collesactualpreferred.php
- template/collesactualpreferred/lang/it/surveyprotemplate_collesactualpreferred.php
- template/collesactualpreferred/tests/behat/graphs.feature
- template/collespreferred/lang/en/surveyprotemplate_collespreferred.php
- template/collespreferred/lang/it/surveyprotemplate_collespreferred.php
- template/collespreferred/tests/behat/graphs.feature
Colles report is divided into three sections: Summary, Scales and Questions.
The first section consists into a single graphic.
It is called by Administration > Surveypro administration > Report > Colles report > summary.
Clicking on the graphic the report changes to Scales section.
This section is a 6 graphs page, one per each Scale: Relevance, Reflective Thinking...
Clicking again on the graphs the report moves to Questions section. This section has 4 graphs per each Scale.
Currently this third section is unique and is build with 6x4 graphs but should be divided into 6 sections of 4 graphs only with corresponding items in the Administration > Surveypro administration > Report > Colles report
> CONTRIB-6493 mod_surveypro: changed navigation in lib.php

- classes/itembase.php
- classes/submission.php
- classes/view_form.php
- field/age/classes/field.php
- field/boolean/classes/field.php
- field/character/classes/field.php
- field/checkbox/classes/field.php
- field/date/classes/field.php
- field/datetime/classes/field.php
- field/multiselect/classes/field.php
- field/radiobutton/classes/field.php
- field/rate/classes/field.php
- field/recurrence/classes/field.php
- field/select/classes/field.php
- field/shortdate/classes/field.php
- field/time/classes/field.php
In the output to PDF of a response the numeric answers were dropped.
This was due to a bad use of the userform_db_to_export parent method.
It was not returning a self-consistent value so...
1) it worked fine for all the child classes calling it AND THEN refining the final output
2) it worked very bad for child classes not having that method at all.
> CONTRIB-6520 mod_surveypro: bad use of parent userform_db_to_export

- lang/en/surveypro.php
- layout_items.php
- version.php
I simply received the request to always leave the add_item drop down menu on top of the page because currently...
- if the survey has no item: the add_item drop down is displayed in second position (the first one is for the master template drop down menu)
- once the survey is no longer empty: the add_item drop down is displayed in first position (the second position is for bulk action drop down menu).
People is complaining this is misleading.
> NOBUG mod_surveypro: leave add_item always on top

- classes/view_form.php
This is a nasty rare issue occurring ONLY when last pages of the survey are not going to be displayed because they only hold child elements that are not supposed to appear because of the answer that their parents received.
> CONTRIB-6533 surveypro: changed drop_jumped_saved_data

- classes/submission.php
Super hidden issue occurring only to people not having enough sex!
Fill a surveypro lying over more than a page.
Fill each element and, when you are at the last page DO NOT SUBMIT
but
return back to the first page selecting `<< previous page` as much time as needed (please, make sex instead).
When you reach the first page select the "Responses" TAB.
Your response is shown as "In progress" in the page (of course, nobody submitted it) and...
if you ask for the PDF you get something that is different from what the export to CSV returns.
The reason is this.
In order to save what the user entered in the form, the save process is performed even when `<< previous` or `pause` buttons are pressed.
When people use the `pause` button they want to save the record EVEN IF THEIR ANSWERS ARE NOT VALID …
> CONTRIB-6534 mod_surveypro: added verified = 1

- classes/itembase.php
- form/items/itembase_form.php
- locallib.php
First: create a branched surveypro with
boolean1 and
boolean2 where boolean2 is conditioned by answer to boolean1 == 1
The condition is well respected at fill time.
Second: create a branched surveypro with
boolean1 and
boolean2 where boolean2 is conditioned by answer to boolean1 == 0
The condition is not respected at fill time.
I fixed this by changing 
if (empty($textareacontent)) {
to
if (!strlen($textareacontent)) {
> CONTRIB-6538 mod_surveypro: changed empty to !strlen

- field/checkbox/classes/field.php
Not mandatory checkbox elements (so, including the "No answer" option) do not disable child elements living in the same page when "No answer" is selected.
I simply added one more js condition to each child element.
> CONTRIB-6545 surveypro: addded js directive for "No answer" option

- classes/view_form.php
I can not imagine how this was possible but not all the instances of "firstpageright" were replaced by "nextpageright"
I am going to merge this issue by myself because #239 has already been merged
> NOBUG mod_surveypro: replacement is now closed

- field/boolean/classes/field.php
- field/checkbox/classes/field.php
- field/integer/classes/field.php
- field/multiselect/classes/field.php
- field/radiobutton/classes/field.php
- field/select/classes/field.php
Deep problem!
Almost all the 6 userform_child_item_allowed_dynamic methods are bad!
Luckily the methods used by boolean and integer (that are the most commonly used) work fine but the problem is still very relevant because those methods are responsible for the evaluation of the input provided by the user.
This is the story.
Parent and child in the same page.
Provide the parent with the answer allowing the child.
The child becomes enabled.
Provide an answer to the child.
Return to parent and change your answer.
At submit time mform submits the answer for the child too!! GRRRR
So, the method userform_child_item_allowed_dynamic verify if the submission was expected and, if needed, it drops it.
> CONTRIB-6546 surveypro: rewritten userform_child_item_allowed_dynamic

- field/boolean/classes/field.php
- field/integer/classes/field.php
- field/radiobutton/classes/field.php
- field/select/classes/field.php
The method used userform_get_parent_disabilitation_info
used to write the js disabilitation commands for children
is usually too complex without any apparent reason.
The code need cleanup.
> CONTRIB-6548 surveypro: userform_get_parent_disabilitation_info cleanup

- classes/utility.php
Create a dummy surveypro (1 element is enough).
Log in as a student.
Fill the survey and submit it.
Log out
Log in as a teacher.
Edit the student response.
Submit it.
After submission EVEN IF THE TEACHER IS NOT ALLOWED TO RESPOND, the "Add one more response" button appear.
By clicking it, an error rise up.
> CONTRIB-6550 mod_surveypro: enforced condition in can_submit_more

- classes/view_export.php
as usual, empty includes answers == 0 and this is not correct!
> CONTRIB-6556 mod_surveypro: replaced `empty` with `!strlen`

- form/items/itembase_form.php
with
commit cd3c2817ac84db408b6f1e18b35f6746d8b1ea7b
Author: Kordan <kordan@mclink.it>
Date:   Wed Sep 21 10:23:27 2016 +0200
CONTRIB-6538 mod_surveypro: changed empty to !strlen
a regression was introduced because some plugin, like pagebreak, doesn't have the parentcontent property and $data['parentcontent'] in form validation is not set. I simply added a check to verify that $data['parentcontent'] is actually set.
> CONTRIB-6657 mod_surveypro: added if ($item->get_insetupform('parentid'))

- tests/behat/parent_radiobutton.feature
A test should be added to verify radiobutton items as parent.
Parent-child relation may be done between items in the same page and in two different pages.
Routines used to display children are different from routines used to enable children so this test should foreseen both cases.
> CONTRIB-6559 mod_surveypro: added parent_radiobutton

- tests/behat/parent_integer.feature
A test should be added to verify integer items as parent.
Parent-child relation may be done between items in the same page and in two different pages.
Routines used to display children are different from routines used to enable children so this test should foreseen both cases.
> CONTRIB-6560 mod_surveypro: added parent_integer

- classes/utility.php
Go to the item list page.
From bulk action menu select 'Delete hidden items' when all items are visible (or the opposite).
Execute the action.
An error is returned because the query does not foresees empty list of affected items.
> CONTRIB-6568 mod_surveypro: triggered empty target

- classes/view_export.php
Something simpler than
[surveypro->name].csv-[date]_[time]-comma_separated.csv
should be provided as name of the file to export data.
In addition, is not clear from the name, if the file content is verbose or raw.
> CONTRIB-6572 mod_surveypro: changed export file name

- field/integer/classes/field.php
it is not possible to arrive in integer userform_save_preprocessing having 
if ($answer['mainelement'] == SURVEYPRO_INVITEVALUE) {
because the submission of this value is not allowed.
Because of this, that method may be simplified.
> CONTRIB-6576 surveypro: simplified integer userform_save_preprocessing

- field/boolean/classes/field.php
it is not possible to arrive in boolean userform_save_preprocessing having 
if ($answer['mainelement'] == SURVEYPRO_INVITEVALUE) {
because the submission of this value is not allowed.
Because of this, that method may be simplified.
> CONTRIB-6577 surveypro: simplified boolean userform_save_preprocessing

- field/numeric/classes/field.php
numeric must save empty string and not null when empty strings are submitted
> CONTRIB-6578mod_surveypro: fixed numeric save_preprocessing

- field/rate/classes/field.php
Each item in surveypro has a unique background colour.
Colours are alternated in the out form.
Rate item is supposed to have a unique background colour too.
If a rate item is not mandatory, the "No answer" checkbox uses a wrong background.
> CONTRIB-6585 modsurveypro: added one color_unifier call

- classes/itemlist.php
- classes/utility.php
- lib.php
Once a submission is deleted, if the course completion is requested, involved users must be selected but this selection must be performed before the submission deletion.
The same is true for item deletion.
> CONTRIB-6571 mod_surveypro: utility cleanup

- classes/itembase.php
- classes/view_form.php
- classes/view_import.php
- db/install.xml
- db/upgrade.php
- field/age/classes/field.php
- field/autofill/classes/field.php
- field/boolean/classes/field.php
- field/character/classes/field.php
- field/checkbox/classes/field.php
- field/date/classes/field.php
- field/datetime/classes/field.php
- field/fileupload/classes/field.php
- field/integer/classes/field.php
- field/multiselect/classes/field.php
- field/numeric/classes/field.php
- field/radiobutton/classes/field.php
- field/rate/classes/field.php
- field/recurrence/classes/field.php
- field/select/classes/field.php
- field/shortdate/classes/field.php
- field/textarea/classes/field.php
- field/textarea/db/install.xml
- field/time/classes/field.php
- version.php
Here the answer content format is finally taken from the editor and no longer set to FORMAT_HTML per default.
If this branch is correct, now it is matter of better manage the export and the import to csv as, currently, with the export->import precess, the answer contentformat is missed.
> CONTRIB-6588 mod_surveypro: correct contentformat at save time

- classes/itembase.php
- classes/itemlist.php
In the element list page, the change of the indent of a fieldset element leads to an error message.
> CONTRIB-6609 mod_surveypro: denied indent change for fieldset

- report/delayedusers/classes/report.php
- report/delayedusers/view.php
Go to a course divided into groups.
Go to a surveypro with some submissions.
Ask for delayed users report.
Select a group different from "All groups".
You will see a list of users.
Filter them with a name in the alphabet.
The group menu returns to "All groups"
> CONTRIB-6635 mod_surveypro: added $groupfilterform->set_data

- report/attachments/classes/report.php
- report/attachments/view.php
Go to a course divided into groups.
Go to a surveypro with some submissions.
Ask for attachments report.
Select a group different from "All groups".
You will see a list of users.
Filter them with a name in the alphabet.
The group menu returns to "All groups"
> CONTRIB-6636 mod_surveypro: added $groupfilterform->set_data

- field/textarea/classes/field.php
If a textarea item is added to a surveypro with only the "trim on save" option, the note displayed in the form starts with a semicolon.
> CONTRIB-6733 mod_surveypro: deleted wrong empty message

- field/datetime/classes/field.php
Create a surveypro with a datetime element.
The search can be performed only using the datetime field. It can't be ignored.
> CONTRIB-6737 mod_surveypro: revision of datetime userform_mform_element

- field/shortdate/classes/field.php
- field/shortdate/form/itemsetup_form.php
Create a surveypro with a shortdate element.
The search can be performed only using the shortdate field. It can't be ignored.
> CONTRIB-6740 surveypro: revision of shortdate userform_mform_element

- report/frequency/classes/report.php
The query in public function get_submissions_sql() of /report/frequency/classes/report.php groups by a.content but doesn't asks ONLY for aggregated data
> CONTRIB-6629 mod_s urveypro: deleted useless fields

- classes/itembase.php
Go to Site administration > Plugins > Activity modules > Surveypro > Surveypro and set "Extra note in search form" to true.
Add a label to a surveypro.
Set it to be available in the search form.
Go to the search form.
The error reported by martinvivek in #322 rise up.
> CONTRIB-6811 mod_surveypro: protected $this->extranote

- format/label/classes/format.php
In the label setup form was added the "Trim on save" checkbox that is a non sense in that form.
Dropped.
> NOBUG mod_surveypro: dropped trimonsave from label setup form

- field/select/classes/field.php
For unknown reasons the id of the select was removed but this was detected by the behat test: "test select setup form". Simple to fix. Misterious the reason why I removed it.
> NOBUG mod_surveypro: added disappeared select id

- field/recurrence/classes/field.php
Adding a "Recurrence" field leaving "Hide filling instruction", "Lower bound" and "Upper boud" untouched, at preview time the following exception rises up:
Exception - Notice: Undefined variable: fillinginstruction in [dirroot]/mod/surveypro/field/recurrence/classes/field.php on line 691
It comes out because $fillinginstruction = something is never executed.
> CONTRIB-6852 mod_surveypro: initialized $fillinginstruction

- tests/behat/lib_behattest.php
The custom behat method stored in tests/behat/lib_behattest.php defines items using, sometimes, bad mform element names.
For instance:
for age plugin it is used lowerbound_year instead of lowerboundyear (and similar);
for autofill plugin it is used element01_select instead of element01select (and similar);
for date plugin it is used lowerbound_day instead of lowerboundday (and similar);
for datetime plugin it is used lowerbound_day instead of lowerboundday (and similar);
for recurrence plugin it is used lowerbound_day instead of lowerboundday (and similar);
for shortdate plugin it is used lowerbound_day instead of lowerboundday (and similar);
for time plugin it is used lowerbound_day instead of lowerboundday (and similar).
> CONTRIB-6853 mod_surveypro: cleaned mform element names

- field/age/classes/field.php
> CONTRIB-6936 mod_surveypro: prefill now includes _noanswer checkbox

- field/shortdate/classes/field.php
> CONTRIB-6938 mod_surveypro: prefill now includes _noanswer checkbox

- field/date/classes/field.php
> CONTRIB-6939 mod_surveypro: prefill now includes _noanswer checkbox

- field/datetime/classes/field.php
> CONTRIB-6940 mod_surveypro: prefill now includes _noanswer checkbox

- field/recurrence/classes/field.php
> CONTRIB-6941 mod_surveypro: prefill now includes _noanswer checkbox

- field/time/classes/field.php
> CONTRIB-6942 mod_surveypro: prefill now includes _noanswer checkbox

- field/checkbox/classes/field.php
> CONTRIB-6935 mod_surveypro: prefill now includes _noanswer checkbox

- layout_items.php
Pushing the up/down icon to reorder the items of the surveypro, the $PAGE url is wrong. I get it by selecting the "Purge all caches" link at the bottom of the page in developer mode.
> CONTRIB-6964 mod_surveypro: added params to url

- field/textarea/classes/field.php
- field/textarea/lang/en/surveyprofield_textarea.php
In the textarea item, the size of the text area is not applied in conjunction with "Use html editor".
This should be explained in the help.
> CONTRIB-6965 mod_surveypro: text revision

- classes/utility.php
- classes/view_form.php
- field/multiselect/backup/moodle2/backup_surveyprofield_multiselect_subplugin.class.php
- field/multiselect/classes/field.php
- field/multiselect/db/install.xml
- field/multiselect/db/upgrade.php
- field/multiselect/form/itemsetup_form.php
- field/multiselect/lang/en/surveyprofield_multiselect.php
- field/multiselect/lang/es_mx/surveyprofield_multiselect.php
- field/multiselect/version.php
- lib.php
Multiselect item is actually affected by a lot of minor and major issues.
It is almost never really used because checkbox item performs the same tasks and this seems to be the reason why none still rose up with a request bug fixes.
Among them:
- the `"No Answer" as default` option is missing in spite of what it has been done for all the other items
- providing a "blank" answer (each item not selected) saves a wrong answer to the database
- the standard used for the value saved to the db is different from the one used for all the other items
> CONTRIB-6952 mod_surveypro: umbrella of fixes for multiselect

- classes/utility.php
- classes/view_form.php
- field/multiselect/backup/moodle2/backup_surveyprofield_multiselect_subplugin.class.php
- field/multiselect/classes/field.php
- field/multiselect/db/install.xml
- field/multiselect/db/upgrade.php
- field/multiselect/form/itemsetup_form.php
- field/multiselect/lang/en/surveyprofield_multiselect.php
- field/multiselect/lang/es_mx/surveyprofield_multiselect.php
- field/multiselect/version.php
- lib.php
Multiselect item is actually affected by a lot of minor and major issues.
It is almost never really used because checkbox item performs the same tasks and this seems to be the reason why none still rose up with a request bug fixes.
Among them:
- the `"No Answer" as default` option is missing in spite of what it has been done for all the other items
- providing a "blank" answer (each item not selected) saves a wrong answer to the database
- the standard used for the value saved to the db is different from the one used for all the other items
> CONTRIB-6952 mod_surveypro: umbrella of fixes for multiselect M31

- classes/itemlist.php
- styles.css
Icons in the "availability" section of the "manageitems" table use width and heigth smaller than the ones used by the cousin icons in the "action" section
> CONTRIB-6963 mod_surveypro: changed icons sizes by css

- field/multiselect/lang/en/surveyprofield_multiselect.php
- field/multiselect/lang/es_mx/surveyprofield_multiselect.php
simple addition of a lang string responsible for 
```javascript
001 Scenario: test multiselect setup form # /Users/stronk7/git_moodle/survey/mod/surveypro/field/multiselect/tests/behat/itemform.feature:8
And I press "Add"                   # /Users/stronk7/git_moodle/survey/mod/surveypro/field/multiselect/tests/behat/itemform.feature:31
debugging() message/s found:
Help contents string does not exist: [noanswerdefault_help, surveyprofield_multiselect]
line 496 of /lib/outputcomponents.php: call to debugging()
line 2351 of /lib/outputrenderers.php: call to help_icon->diag_strings()
line 2018 of /lib/formslib.php: call to core_renderer->help_icon()
line 73 of /mod/surveypro/field/multiselect/form/itemsetup_form.php: call to MoodleQuickForm->addHelpButton()
line 204 of /lib/formslib.php: …
```
> NOBUG mod_surveypro: one more lang string

- tests/fixtures/usertemplate/MMM_2015123000.xml
- tests/fixtures/usertemplate/parent-child_2015123000.xml
Modified xml for multiselect elements in order to fix 
```javascript019 Scenario: load and save a usertemplate            # /Users/stronk7/git_moodle/survey/mod/surveypro/tests/behat/usertemplate_create.feature:8
And I set the following fields to these values: # /Users/stronk7/git_moodle/survey/mod/surveypro/tests/behat/usertemplate_create.feature:36
Select option with value|text "(Course) MMM_2015123000.xml" not found. (Behat\Mink\Exception\ElementNotFoundException)```
> NOBUG mod_surveypro: fixed bad multiselect xml

- .travis.yml
Link: https://github.com/moodlerooms/moodle-plugin-ci
As far as our master is only for MOODLE_32_STABLE and up, and that matches the plugin-ci above min version, better we move there. That will show us new problems to fix and better control of them:
- .feature files.
- .js and .css files.
behat still cannot run (timeout) and there is some other problem, but better be using the new version.
> NOBUG surveypro: Move to moodle-plugin-ci v2

- tests/fixtures/usertemplate/multiselect_only_2015123000.xml
fix for
```javascript
004 Scenario: load and apply each usertemplate        # /Applications/MAMP/htdocs/head/mod/surveypro/tests/behat/usertemplate_applyall.feature:8
And I set the following fields to these values: # /Applications/MAMP/htdocs/head/mod/surveypro/tests/behat/usertemplate_applyall.feature:52
Select option with value|text "(Course) age_only_2015123000.xml" not found. (Behat\Mink\Exception\ElementNotFoundException)
```
> NOBUG mod_surveypro: added missing <noanswerdefault> tag

- report/colles/classes/report.php
- template/collesactual/tests/behat/graphs.feature
- template/collesactualpreferred/tests/behat/graphs.feature
- template/collespreferred/tests/behat/graphs.feature
Simply returning to report home, the "Page administration menu" become available once again.
This patch fixes:
001 Scenario: apply COLLES (Actual) master template, add a record and call reports           # /Users/stronk7/git_moodle/survey/mod/surveypro/template/collesactual/tests/behat/graphs.feature:26
And I navigate to "Scales" node in "Surveypro administration > Report > Colles report" # /Users/stronk7/git_moodle/survey/mod/surveypro/template/collesactual/tests/behat/graphs.feature:84
Page administration menu is not found not found. (Behat\Mink\Exception\ElementNotFoundException)
002 Scenario: apply COLLES (Preferred and Actual) master template, add a record and call reports # /Users/stronk7/git_moodle/survey/mod/surveypro/template/collesactualpreferred/tests/behat/graphs.feature:26 …
> NOBUG mod_surveypro: added click on div

- tests/behat/navigation.feature
Added few details to behat test in order to make it properly running in boost and clean both.
The failing test was:
```script
Scenario: select each available link as a teacher # /Applications/MAMP/htdocs/master/mod/surveypro/tests/behat/navigatio
n.feature:27
And I follow "Element"                          # /Applications/MAMP/htdocs/master/mod/surveypro/tests/behat/naviga
tion.feature:39
The "(//html/.//a
[./@href][((./@id = 'Element' or contains(normalize-space(string(.)), 'Element') or contains(./@title, 'Element')
or contains(./@rel, 'Element')) or .//*[(contains(concat(' ', @class, ' '), ' icon ') or name() = 'img') and (contains(
./@alt, 'Element') or contains(./@title, 'Element'))])] | //html/.//*
[translate(./@role, 'ABCDEFGHIJKLMNOPQRSTUVWXYZ', 'abcdefghijklmnopqrstuvwxyz') = …
```
> NOBUG mod_surveypro: fix for behat test in boost

- form/items/itembase_form.php
- styles.css
Last example in the branching section of the element creation form is misaligned in boost.
In spite of this, all is fine in clean.
I replaced the \<ul>\<li> structure with a table and the validator is still happy.
> NOBUG mod_surveypro: examples are not aligned in boost

- classes/itembase.php
The error was because the code was collecting each preexisting 'variable name' in a associative array.
The problem rose up because the index of the array was, badly, the plugin id and not, as it is correct, the id of the element in the surveypro. This lead to deletions of elements with the same index (and this was possible because each plugin starts with element id = 1) from the array of previous variable name and the routine failed.
> CONTRIB-7112 mod_surveypro: changed id with itemid

- field/fileupload/backup/moodle2/backup_surveyprofield_fileupload_subplugin.class.php
- field/fileupload/classes/field.php
- field/fileupload/db/install.xml
- field/fileupload/db/upgrade.php
- field/fileupload/version.php
This PR was opened on top of "aligned backup to tables structure" #390 because I needed well written xml table structures, well written install.xml and well written backup structures before editing them.
This issue rose up because moodle HQ added to the fileupload element a note listing the allowed extensions. Because of this my instructions are no longer needed.
In the frame of this branch I also added three not relevant changes.
The first
- I added to backup_surveyprofield_integer_subplugin.class.php the field 'hideinstructions' that was missing
- I changed the position of 'hideinstructions' into the field/integer/db/install.xml. Useless but homogeneous with the other plugins.
The second: 
- I added to backup_surveyprofield_time_subplugin.class.php the field 'step' that was missing.
The …
> NOBUG mod_surveypro: removed fileupload fillinginstruction

- classes/usertemplate.php
incredible but... hide_items is a function name that has never been used. This wrong name is there since its first implementation. I really can't believe this.
> NOBUG mod_surveypro: changed old function name

- template/collesactual/template.xml
- template/collesactualpreferred/template.xml
- template/collespreferred/template.xml
- template/criticalincidents/template.xml
- tests/fixtures/usertemplate/MMM_2015123000.xml
- tests/fixtures/usertemplate/parent-child_2015123000.xml
- tests/fixtures/usertemplate/textarea_only_2015123000.xml
XML of templates having textarea element were not loaded because the tag <trimonsave> was missing.
> NOBUG mod_surveypro: added missing trimonsave to textarea xml

- classes/reportbase.php
- classes/view_export.php
- form/data/export_form.php
- report/attachments/classes/report.php
The export form was using $this->surveypro->anonymous that does not exist.
The correct one is: $surveypro->anonymous
Very silly PR.
> replaced ! with the more readable empty

- lang/en/surveypro.php
This morning during a demonstration, people asked me why the download format was not respected in raw format data export. The right answer is: "because it must not be respected in favour of the raw format"... but this should be decalred somewhere.
> changed misleading string

- field/age/form/itemsetup_form.php
- field/autofill/form/itemsetup_form.php
- field/boolean/form/itemsetup_form.php
- field/character/form/itemsetup_form.php
- field/checkbox/form/itemsetup_form.php
- field/date/form/itemsetup_form.php
- field/datetime/form/itemsetup_form.php
- field/fileupload/form/itemsetup_form.php
- field/integer/form/itemsetup_form.php
- field/multiselect/form/itemsetup_form.php
- field/numeric/form/itemsetup_form.php
- field/radiobutton/form/itemsetup_form.php
- field/rate/form/itemsetup_form.php
- field/recurrence/form/itemsetup_form.php
- field/select/form/itemsetup_form.php
- field/shortdate/form/itemsetup_form.php
- field/textarea/form/itemsetup_form.php
- field/time/form/itemsetup_form.php
- format/fieldset/form/itemsetup_form.php
- format/fieldsetend/form/itemsetup_form.php
- format/label/form/itemsetup_form.php
- format/pagebreak/form/itemsetup_form.php
- layout_itemsetup.php
Fixed the warning in each of its occurrences:
```
------------------------------------------------------------------------------------------------------------------------
FOUND 0 ERRORS AND 1 WARNING AFFECTING 1 LINE
------------------------------------------------------------------------------------------------------------------------
38 | WARNING | Duplicate class name "mod_surveypro_itemsetupform" found; first defined in
|         | /home/travis/build/moodle/mod/surveypro/field/age/form/itemsetup_form.php on line 38
------------------------------------------------------------------------------------------------------------------------
```
> changed the name of the duplicate classes

- classes/itemlist_variable.php
There was a silly missing assignment in public static function update($itemid, $newvarname) { for variable quick change that was not allowing the verification of the uniqueness of the variable name. Fixed.
> forced different var in var quickchange

- classes/view_export.php
If records are not sorted by submissionid then output_to_xls (or output_to_csv) adds one more line to the output file each time it meets a record with submissionid different from the one of the previous record.
> added missing sort for usual export

- classes/view_export.php
- form/data/export_form.php
- view_export.php
The two items "download attachments by user to zip" and "download attachments by item to zip" are not welcome in the "download file type" drop down menu of the administration > Survey > Export form if the surveypro has not items with type = 'fileupload'
> conditionally add items

- field/age/classes/field.php
- field/boolean/classes/field.php
- field/character/classes/field.php
- field/checkbox/classes/field.php
- field/date/classes/field.php
- field/datetime/classes/field.php
- field/fileupload/classes/field.php
- field/integer/classes/field.php
- field/multiselect/classes/field.php
- field/numeric/classes/field.php
- field/radiobutton/classes/field.php
- field/recurrence/classes/field.php
- field/select/classes/field.php
- field/shortdate/classes/field.php
- field/textarea/classes/field.php
- field/time/classes/field.php
Items with question diaplayed on a "dedicated line" in "full width" mode are never marked as required even when they should be.
> star marking required field is now always displayed

- field/select/classes/field.php
- field/select/lang/en/surveyprofield_select.php
- field/select/lang/es_mx/surveyprofield_select.php
- field/select/lang/it/surveyprofield_select.php
The select plugin was not checking the field "_text" when the option "other" was selected.
> added code to detect empty "other" text

- classes/mastertemplate.php
This issue is quite strange.
Surveypro installed on a linux like server creates correct master-templates.
Once installed over windows server, creates master-templates with lines not wrapping at their end.
By replacing (as I did a long time ago) "\n" with PHP_EOL files are simple to read (they have correct line wrapping) BUT codechcker says: `File has mixed line endings; this may cause incorrect results
End of line character is invalid; expected "\n" but found "\r\n"`
I prefer to have a code difficult to read than resulting in "incorrect results".
Anyway, this issue remain a mistery.
Any suggestion?
> replaced PHP_EOL with "\n" as it was in the remote past

- classes/view_export.php
In MS Azure if the name of the surveypro instance has accented characters or is longer than 80 characters, the zip file with the name of the the surveypro instance is not created because of a permission problem.
> shortened filename because of MS Azure limitation

- field/character/classes/field.php
Saving a surveypro to usertemplate it was saved a wrong content in the pattern field.
Actually, when the surveypro designer choose to have a character item using regex validation, the pattern field is supposed to hold the regex anf not the kind of validation required.
The same behaviour was already in use for custom pattern.
> added condition for regex pattern

- field/autofill/classes/field.php
A submission search using the autofill field was not successfull using substrings.
Now it is, so if my autofill field holds the user fullname, for instance, I can also search for the submissions of that user writing only a part of his/her name.
> added response_get_whereclause to autofill

- form/outform/fill_form.php
A long time ago for surveypros spanning more pages when the user paused a submission, the current page was not saved.
In that situation the surveys with only one page were forced to neglect the allowpauseresume option.
Now the current page is actually saved so even if the survey lies on a single page the "Pause" button should be displayed.
> Removed useless if

- tests/behat/multilang_mastertemplate.feature
I don't understand why but `I expand "Argomento x" node` doesn't rise up an error but, at the same time, doesn't expand the node.
I replaced it.
> fixed behat syntax

- classes/formbase.php
- classes/layout.php
- classes/submission.php
- classes/utility.php
- classes/view_cover.php
- layout_itemlist.php
Having a layout with 1 input item and many format items, the reorder icon was not displayed in layout->elements
This was caused by the wrong count of elements. Only input items were cunted and not ALL the items.
> Generalised the has_input_items to layout_has_item

- classes/layout.php
After the item deletion action, if the user reload the page, the deletion is performed again rising up an error.
If the item to drop is not in the db, this means that the user already deleted it and is reloading the page.
In this case, stop the deletion execution.
> added code to drop unexpected reload

- tests/lib_test.php
This is a simple example of unit test covering 1 global method (````surveypro_cutdownstring()````).
Right now it's failing, because the method being tested does not work ok with UTF-8 chars. But once #519 is implemented, if it's correct... then the test should start to pass.
It shows how phpunit data providers work and the same approach can be used to any other function not needing generators (that we don't have yet). But it's a good example that can be applied to other code (lib.php, helpers...).
Ciao :-)
> Example unit test covering a global function using data provider

- field/textarea/classes/field.php
In the way of using right content format instead of bloody embedded FORMAT_HTML, now the answer provided by the user uses the right contentformat too.
> changed embedded FORMAT_HTML with $fromdb->contentformat

- classes/itembase.php
- classes/view_import.php
- field/age/classes/field.php
- field/autofill/classes/field.php
- field/boolean/classes/field.php
- field/character/classes/field.php
- field/checkbox/classes/field.php
- field/date/classes/field.php
- field/datetime/classes/field.php
- field/fileupload/classes/field.php
- field/integer/classes/field.php
- field/multiselect/classes/field.php
- field/numeric/classes/field.php
- field/radiobutton/classes/field.php
- field/rate/classes/field.php
- field/recurrence/classes/field.php
- field/select/classes/field.php
- field/shortdate/classes/field.php
- field/textarea/classes/field.php
- field/time/classes/field.php
- format/fieldset/classes/format.php
- format/fieldsetend/classes/format.php
- format/label/classes/format.php
- format/pagebreak/classes/format.php
Following the style used in #534 (and suggested in #527) I wrote this PR. The property $usepositionalanswer is no longer used and is replaced by get_uses_positional_answer method.
> replac. $usepositionalanswer prop. with get_uses_positional_answer meth.

- .travis.yml
recent changes in travis infrastructure (xenial now default)
requires it to be explicitly installed (via addon or service)
> Make mysqli tests back to pass

- .travis.yml
Not sure why it worked ok in my original commit. Anyway, it seems
that's the way recommended for travis (will use mysql 5.7 by
default on xenial
> Move mysql to services

- classes/mastertemplate.php
I got a strange error. It is the first time I get it.
Generating a master template an error execution stopped the process.
The error arrived because
$masterfilelist was different from $templatemastercontent
and
if ($masterfilelist !== $templatemastercontent) {
triggered the possible security issue.
Going to investigate about the issue I found that the templatemastercontent (what I expect to have in the folder)
was:
```
Array (
[0] => classes/privacy/provider.php
[1] => classes/template.php
[2] => lang/en/surveyprotemplate_pluginname.php
[3] => pix/icon.png
[4] => pix/icon.svg
[5] => template.xml
[6] => version.php
)
```
while $masterfilelist (what actually is in the folder) was:
```
Array (
[0] => classes/privacy/provider.php
[1] => classes/template.php
[2] => …
```
> Fixed folder content validation

- classes/layout.php
- styles.css
Once arrived in boost I finally found a way to order icons in Layout > Elements by columns even if an icon in the set is not displayed for some reason.
> icons of Layout > Elements are now ordered in columns

- field/boolean/classes/field.php
- field/checkbox/classes/field.php
- field/integer/classes/field.php
- field/multiselect/classes/field.php
- field/radiobutton/classes/field.php
- field/select/classes/field.php
- mod_form.php
running surveypro after more than an year, I found "Deprecated: implode(): Passing glue string after array is deprecated. Swap the parameters in /Applications/MAMP/htdocs/master/mod/surveypro/mod_form.php on line 209"
> swapped params in wrong implode($array, $separator)

- .github/workflows/moodle-ci.yml
As far as now travis is not free, GHA provides basically the same.
Once this is merged, for every pull request or change to the repository... you'll get this done:
https://github.com/stronk7/moodle-mod_surveypro/actions/runs/507345028
Note that right now both phpdoc and behat are failing, but that's ok, should be fixed in other changes.
> Add GitHub Actions (GHA) basic support

- .github/workflows/moodle-ci.yml
- .travis.yml
Update to moodle-plugin-ci v3
This just updates to current moodle-plugin-ci v3 and renew
the combinations tested to current ones, matching the GHA ones.
Note this is built on top of #557 and needs to be merged AFTER it.
> Update to moodle-plugin-ci v3

- classes/utility_mform.php
Running behat test I found: 
Deprecated: Array and string offset access syntax with curly braces is deprecated in /Applications/MAMP/htdocs/master/mod/surveypro/classes/utility_mform.php on line 54
> replaced curly braces with brackets

- .github/workflows/moodle-ci.yml
Following the 3.0.5 release of moodle-plugin-ci, where a bug
was fixed and requires to add a new line to the install script.
See ACTION REQUIRED:
https://github.com/moodlehq/moodle-plugin-ci/releases/tag/3.0.5
> Get nodejs correct version installed

- classes/view_export.php
Trying to export all the saved answers of a surveypro to a file, 
if (empty($this->surveypro->anonymous) || ($forceuserid)) {
the query to select records contains the syntax error 'u.id as userid, , u.id, u.picture'
> Syntax error in query

- form/mtemplates/apply_form.php
- layout_itemlist.php
- mtemplate_apply.php
Replaced `inline` variable name with a simpler to understand `subform` variable name
> Replaced `inline` with  `subform`

- classes/view_form.php
- classes/view_search.php
With the introduction of interactive fieldset those format elements are now equipped with open/close triangle and they submit their own state. Because of this the paused survey tries to save the information submitted by interactive fieldset. This causes the "Call to undefined method mod_surveypro_utility_layout::delete_answer()"
> Fixed the way to filter what student submits

- classes/itembase.php
- field/boolean/tests/behat/customnumebr_inclusion.feature
I was addressed to find a way to include the question custom numer into the question content putting it close to the displayed text and not before the html tag <p>
Some examples:
Given
```'Is it true?'```
I want to get
```$customnumber.': '.'Is it true?'```
Given
```'<p>Is it true?</p>'```
I want to get
```'<p>'.$customnumber.': '.'Is it true?</p>'```
Given
```'<p dir="ltr">Is it true?</p>'```
I want to get
```'<p dir="ltr">'.$customnumber.': '.'Is it true?</p>'```
Given
```'<p dir="ltr"><em>Is it true?</em></p>'```
I want to get
```'<p dir="ltr">'.$customnumber.': '.'<em>Is it true?</em></p>'```
Given
```'<p><p dir="ltr">Is it true?<br></p></p>'```
I want to get
```'<p><p dir="ltr">'.$customnumber.': '.'Is it true?<br></p></p>'```
> Rewritten the regex to include customnumber

- classes/reportbase.php
- classes/tabs.php
- classes/utility_layout.php
- classes/view_cover.php
- lang/en/surveypro.php
- lib.php
- report/attachments/view.php
- report/colles/classes/report.php
- report/colles/view.php
- report/delayedusers/view.php
- report/frequency/view.php
- report/responsesperuser/view.php
- report/userspercount/view.php
- tests/behat/navigation.feature
After a so long time far from surveypro I found that reports had the same dignity of usertemplate or mastertemplates but were sublocated in the child tab as a page of survey TAB.
This sounds not correct to my eyes today so I created the parent TAB_REPORT and I moved reports as its pages.
> Upgrades report to parent TAB

- backup/moodle2/restore_surveypro_activity_task.class.php
With that, the PHPDoc check in the GHA CI runs should be back to pass.
> Fix some small phpdocs details

- report/lateusers/classes/report.php
The idea is: if the user is allowed to pause/resume the survey he has to be counted among late users if he didn't submit its answer OR if he submitted only IN PROGRESS responses.
Further more... if the required conditions are defined as "The user has to sumbit at least x responses" the user has to be considered "late user" if he submitted AS CLOSED less than x responses.
> Changed standing report query

- classes/view_cover.php
- lang/en/surveypro.php
- lang/es/surveypro.php
- lang/es_mx/surveypro.php
- lang/it/surveypro.php
Since the inclusion of completion detail (#617) into surveypro the specification of opening and closing dates and few more details in surveypro cover page has become redundant.
> Deleted redundand info from cover

- layout_itemlist.php
- layout_preview.php
- layout_validation.php
- mtemplate_apply.php
- mtemplate_save.php
- report/attachments/view.php
- report/colles/view.php
- report/frequency/view.php
- report/lateusers/view.php
- report/responsesperuser/view.php
- report/userspercount/view.php
- utemplate_apply.php
- utemplate_import.php
- utemplate_manage.php
- utemplate_save.php
- view.php
- view_export.php
- view_import.php
- view_submissions.php
Tiny issue fixed.
When pages layout_itemlist.php, layout_preview.php, view.php and view_submissions.php were called passing them 's' and not 'id' the "Blocks editing on\off" button was no longer working. Super simple fix.
> added 'Blocks editing on\off' everywere

- classes/tabs.php
- classes/utility_layout.php
- classes/view_cover.php
- lib.php
- report/attachments/classes/filterform.php
- report/attachments/classes/form.php
- report/attachments/classes/groupjumperform.php
- report/attachments/classes/report.php
- report/attachments/uploads.php
- report/attachments/view.php
- report/colles/classes/groupjumperform.php
- report/colles/classes/report.php
- report/colles/graph.php
- report/colles/view.php
- report/frequency/classes/filterform.php
- report/frequency/classes/report.php
- report/frequency/graph.php
- report/frequency/view.php
- report/lateusers/classes/groupjumperform.php
- report/lateusers/classes/report.php
- report/lateusers/view.php
- report/responsesperuser/classes/groupjumperform.php
- report/responsesperuser/classes/report.php
- report/responsesperuser/view.php
- report/userspercount/classes/groupjumperform.php
- report/userspercount/classes/report.php
- report/userspercount/view.php
- tests/behat/submission_test.feature
Running the attachment report it is possible to ask for details of each attachment. If they are requested the page diplaying them uses "Report" as page and not as TAB.
Branch build on top of "namespace added to reports too" (#637)
> Attachment report wrong tab

- .github/workflows/moodle-ci.yml
Just that, keep 2 jobs (postgres and mariadb), with 2 PHP versions (max and min for that branch). Both jobs running with 311 SP and 311 Moodle.
> Make SP 311 to only be tested against 311_STABLE Moodle

- classes/view_export.php
At the end of the export to excel of saved responses the "Continue" form button was unexpectedly disabled.
This is an issue if people ask to download to excel twice (for instance for "closed" and "in progress" responses separately).
It seems that dropping "return true" or changing it with exit; fixes the issue.
> Dropped "return true" to keep the button enabled

- classes/layout_itemsetup.php
- styles.css
- Relation table sorting is useless as each child must be after the parent
- The best place for parent constraints are in the frame of the parent item
- Relation icons are not well separated as in the item table
- Header of the plugin column is not well vertically aligned
> Fixed few  minor details of the relation table

- classes/layout_itemsetup.php
- classes/layout_preview.php
- classes/tabs.php
- classes/usertemplate.php
- classes/view_form.php
- classes/view_submissions.php
- field/autofill/classes/item.php
- field/radiobutton/classes/item.php
- report/attachments/classes/form.php
- report/attachments/classes/report.php
Following the Code Checker report
each instance of print_error has been replaced with new moodle_exception leaving passed parameters untouched.
> replaced print_error with throw new moodle_exception

- classes/event/abandoned_submission_deleted.php
- classes/event/mail_neverstarted_sent.php
- classes/event/mail_oneshotmp_sent.php
- classes/event/mail_pauseresume_sent.php
- classes/task/delete_abandoned_submissions.php
- classes/task/mail_neverstarted.php
- classes/task/mail_oneshotmp.php
- classes/task/mail_pauseresume.php
- lang/en/surveypro.php
- lang/it/surveypro.php
- version.php
Three logs were added:
1) logs for email sent because of never started surveys
2) logs for email sent because of abandoned one page surveys
3) logs for email sent because of abandoned survey where pause/resume is allowed.
Classes in surveypro/classes/event were purged of unused methods.
The message is so simple that there is non need of $this->other[] params.
The function validate_data() was conseguently dropped.
Tested only for never started surveys.
> Added logs for reminder emails

- tests/behat/duplicate_response.feature
Fixed the only survived issue (only using suite=default):
001 Scenario: Duplicate a response # /Applications/MAMP/htdocs/stable/mod/surveypro/tests/behat/duplicate_response.feature:8
And I follow "Responses"     # /Applications/MAMP/htdocs/stable/mod/surveypro/tests/behat/duplicate_response.feature:61
The "(//html/.//a
[./@href][((./@id = 'Responses' or contains(normalize-space(string(.)), 'Responses') or contains(./@title, 'Responses') or contains(./@rel, 'Responses')) or .//*[(contains(concat(' ', @class, ' '), ' icon ') or self::img) and (contains(./@alt, 'Responses') or contains(./@title, 'Responses'))])] | //html/.//*
[translate(./@role, 'ABCDEFGHIJKLMNOPQRSTUVWXYZ', 'abcdefghijklmnopqrstuvwxyz') = 'link'][((./@id = 'Responses' or contains(./@value, 'Responses')) or …
> Added 'page in tab bar' to 'And I follow "Responses"'

- classes/view_cover.php
- classes/view_submissions.php
- tests/behat/reserved_at_first.feature
- view_form.php
Let's suppose a surveypro having only reverved items in the first page.
When the simple user starts to fill the form, he/she can not go to the first page of the surveypro BY DEFAULT but there must be a check for the first availab
le page.
This routine adds the described check.
This PR has been created on top of #713.
> Reserved at first rev2

- classes/view_cover.php
- classes/view_form.php
- classes/view_submissions.php
- tests/behat/modificationdate.feature
- tests/behat/reserved_at_first.feature
- view_form.php
Even filling a multipage surveypro moving forward and backword, timemodified is recorded ONLY at modification time
> No modification time at first submit

- classes/itembase.php
- classes/layout_itemsetup.php
- classes/view_form.php
- format/fieldsetend/classes/item.php
- format/pagebreak/classes/item.php
A surveypro coming from a mastertemplate is multilanguage.
None is allowed to edit the survey.
Admins can edit strings changing lang files of the plugin.
If a teacher choose to edit the surveypro he MUST drop the languages.
I fixed the routine that drop languages.
> Rewritten the routine to delete multilang support

- classes/formbase.php
Queries involving the database field surveypro_answer.plugin don't need $DB->sql_compare_text and I deleted it. I am not sure about surveypro_answer.content and for this reason I leave it as it was. (at the moment).
> Replaced useless $DB->sql_compare_text

- classes/view_export.php
Even if a surveypro has a name using multilang syntax like, for instance, '\<span lang="it" class="multilang"\>Buongiorno mondo\</span\>\<span lang="en" class="multilang"\>Hello world\</span\>', the name of the file to export responses has to be 'Hello world' and not all the multilang syntax.
> Added format_text to fix file name

- classes/view_submissions.php
I found 2 bloody issues that I tried to fix with this patch.
1st: a set of lines of code was duplicated. 
2nd: the variable $allowed was used to check the permission of the user to...
- perform an action
- see a response in readonly mode or in edit mode.
The bug was that using the same variable, if the action was not allowed the variable "$allowed" was set to false but if the following access to the response was allowed, then the same variable was overwritten to true and the NOT ALLOWED action was executed.
This is why I added in the middle between the two different checks
```
if (!$allowed) {
throw new \moodle_exception('incorrectaccessdetected', 'mod_surveypro');
}
```
> Enforced prevent_direct_user_input

- classes/view_export.php
I didn't remove that line to save time but because for multilang names I had (from line 229)
`$filename = '<a class="autolink" title="prova" href="http://localhost:8888/MOODLE_311_STABLE/mod/surveypro/view.php?id=14">prova</a>'`
and using (in line 244) the removed
`$filename = clean_filename($filename);`
I got
`$filename = 'a class=autolink title=prova href=httplocalhost8888MOODLE_311_STABLEmodsurveyproview.php?id=14provaa closed verbose 202210251144.csv'`
while I only want: 'prova closed verbose 202210251155.csv'
> Removed a redundant clean

- .github/workflows/moodle-ci.yml
If all the tests end passing and without any warning, this can be considered. Let' see.
It just updates a few components and remove not needed ones. Should be enough to avoid some warnings and be ready for future Moodle versions (like 4.2) that have higher database requirements.
Ciao :-)
> Small updates to GHA to avoid some warnings and bump versions

- classes/view_form.php
Even if each answer in the submission is provided and well formed, the user is allowed to close the submission only by pressing the 'save' button or, if available, the 'save as' button.
> Do not close the submission when pressing 'Next page >>' button

- classes/itembase.php
- classes/mastertemplate.php
- classes/reportbase.php
- classes/tabs.php
- classes/utility_layout.php
- classes/view_cover.php
- field/textarea/mform/textarea_editor.php
- field/textarea/mform/textarea_plain.php
- lib.php
- report/attachments/classes/report.php
- report/attachments/view.php
- report/colles/classes/report.php
- report/colles/view.php
- report/frequency/classes/report.php
- report/frequency/view.php
- report/lateusers/classes/report.php
- report/lateusers/view.php
- report/responsesperuser/classes/report.php
- report/responsesperuser/view.php
- report/userspercount/classes/report.php
- report/userspercount/view.php
- template/collesactual/tests/behat/graphs.feature
- template/collesactualpreferred/tests/behat/graphs.feature
- template/collespreferred/tests/behat/graphs.feature
- tests/behat/gdpr_anonimity.feature
Because of GDPR user names are not going to be shared.
Now, if the surveypro is anonymous then each user without capability 'mod/surveypro:alwaysseeowner' is NOT supposed see user names.
Users with 'mod/surveypro:alwaysseeowner' can still see them.
> Added check over report writing names

- field/textarea/mform/textarea_editor.php
Declaration of surveyproform_textarea_editor::getFrozenHtml() is now compatible with MoodleQuickForm_editor::getFrozenHtml()
> Added compatibility between parent and child methods

- classes/view_form.php
- classes/view_search.php
- field/age/classes/item.php
- field/autofill/classes/item.php
- field/boolean/classes/item.php
- field/character/classes/item.php
- field/checkbox/classes/item.php
- field/date/classes/item.php
- field/datetime/classes/item.php
- field/fileupload/classes/item.php
- field/integer/classes/item.php
- field/multiselect/classes/item.php
- field/numeric/classes/item.php
- field/radiobutton/classes/item.php
- field/rate/classes/item.php
- field/recurrence/classes/item.php
- field/select/classes/item.php
- field/shortdate/classes/item.php
- field/textarea/classes/item.php
- field/time/classes/item.php
I removed from $itemhelperinfo array the two elements: $surveyproid and $submissionid.
Those elements are the same for each item of the form and do not need to be specified for each single item.
They are 100% waste of memory.
> Reduce resources to save submissions

- db/access.php
From this branch onwards my target is surveypro for moodle4.
I would like to change the GTA matrix from:
```
matrix:
include:
- php: 8.0
moodle-branch: MOODLE_311_STABLE
database: pgsql
suite: default
profile: chrome
- php: 7.3
moodle-branch: MOODLE_311_STABLE
database: mariadb
suite: classic
profile: default
```
to
```
matrix:
include:
- php: 8.0
moodle-branch: MOODLE_401_STABLE
database: pgsql
suite: default
profile: chrome
- php: 7.4
moodle-branch: MOODLE_401_STABLE
database: mariadb
suite: classic
profile: default
```
but the process to have all the behat test successfull in surveypro for moodle4 using --suite=default needs a lot of changes in the code. In order to manage this process I divide it in a long stack of branches. Each branch is part of a bigger design that I am tring to …
> Renamed two capabilities

- classes/view_submissions.php
I found that the action download to pdf of a response, that is now correctly checked before the execution, was wrongly denied.
This patch needs to be applied to sPro for M311 anf to sPro for M401.
> Allowed the dw2pdf action

- classes/privacy/provider.php
- classes/tools_import.php
- classes/view_submissions.php
- field/numeric/tests/behat/multiformat.feature
- index.php
- report/colles/graph.php
- tests/behat/behat_mod_surveypro.php
- tests/behat/multilang_mastertemplate.feature
- tests/lib_test.php
According to MDL-65612 it was changed the way to access the language menu in .feature files.
In the frame of this same branch some useless spces invalidating the PR were dropped out.
> switched from no longer working behat method

- classes/view_submissions.php
If a surveypro is set to anonymous
and a user not having the capabliity 'mod/surveypro:alwaysseeowner'
downloads a response in PDF
he MUST not find the name of the owner of the response in the header of the page .
> No name in PDF header for anonymous sPro

- classes/tabs.php
Here I fixed a silly issue that caused the selection of the wrong page (second level tab) of the tab "Reports".
This branch has to be applied to MOODLE_311_STABLE and, maybe, to MOODLE_401_STABLE.
In MOODLE_401_STABLE this branch is 100% useless as I am going to get rid of tabs and subtabs (second level tab) replacing them with the common GUI according to the other modules.
> Fixed selected report page MASTER

- field/fileupload/lib.php
- lib.php
Maybe it should be better to replace
```
$file = $fs->get_file_by_hash(sha1($fullpath));
if (!$file || $file->is_directory()) {
return false;
}
```
with
```
$file = $fs->get_file_by_hash(sha1($fullpath));
if (!$file || $file->is_directory()) {
send_file_not_found();
}
```
at line 74 of surveypro/field/fileupload/lib.php?
> Replaced || with or

- classes/view_submissions.php
As workaround of the TCPDF library bug commented in https://github.com/moodle/moodle/blob/MOODLE_311_STABLE/dataformat/pdf/classes/writer.php#L109 I replaced the direct link to the picture with the picture encoded file.
> Replaced direct link with base64 encoded file (master)

- classes/utility_item.php
Under special circumstancies the function multilinetext_to_array was not returning an array as it should
> now multilinetext_to_array always returns array

- tests/behat/usertemplate_apply.feature
- tests/behat/usertemplate_applyall.feature
- tests/behat/usertemplate_create.feature
- tests/fixtures/usertemplate/MMM_2023103100.xml
- tests/fixtures/usertemplate/age_only_2023103100.xml
- tests/fixtures/usertemplate/date_only_2023103100.xml
- tests/fixtures/usertemplate/dateshort_only_2023103100.xml
- tests/fixtures/usertemplate/datetime_only_2023103100.xml
- tests/fixtures/usertemplate/parent-child_2023103100.xml
- tests/fixtures/usertemplate/recurrence_only_2023103100.xml
- tests/fixtures/usertemplate/time_only_2023103100.xml
Changed user templates in test/fixtures/usertemplates as the different management of the time (now it is no longer time-zone dependent) causes different way to save defaults, lowerbound and upperbound at item creation).
The idea is: if my answer to the question: "At what time you love to get dinner?" is "8 pm" then, even if you live in a place with a different time zone then your time-zone, when you go to read my answer you have to read "8 pm" and not the time at your cloch when it is 8 pm at my clock.
> Renewed outdated utemplates

- report/attachments/classes/filterform.php
Without going deep in the semantic of the code, I think that the query starting in 
https://github.com/kordan/moodle-mod_surveypro/blob/master/report/attachments/classes/filterform.php#L89
is objectively unnecessarily complex.
I would simplify it as follows
From:
```
$sql = 'SELECT DISTINCT u.id as userid'.$userfieldsapi->selects.'
FROM {user} u
JOIN {surveypro_submission} s ON s.userid = u.id
JOIN ('.$enrolsql.') eu ON eu.id = u.id
JOIN {role_assignments} ra ON ra.userid = u.id
WHERE surveyproid = :surveyproid
ORDER BY u.lastname ASC';
```
to:
```
$sql = 'SELECT DISTINCT u.id as userid'.$userfieldsapi->selects.'
FROM {user} u
JOIN {surveypro_submission} s ON s.userid = u.id
JOIN ('.$enrolsql.') eu ON eu.id = u.id
WHERE surveyproid = :surveyproid
ORDER BY u.lastname ASC';
```
Do you …
> removed an apparently useless join

- classes/itembase.php
- classes/layout_itemsetup.php
- classes/privacy/provider.php
- classes/usertemplate.php
- classes/utility_layout.php
- field/age/classes/item.php
- field/date/classes/item.php
- field/datetime/classes/item.php
- field/recurrence/classes/item.php
- field/shortdate/classes/item.php
- field/time/classes/item.php
- format/pagebreak/classes/item.php
- lib.php
In the frame of this PR I:
-> renamed the method "reset_items_pages" to "reset_pages"
-> reordered few methods grouping the by topic
-> added (and this is a focal point) $this->reset_pages(); at the end of utility_layout->items_set_visibility. There was an issue: I had a surveypro spanning three pages. I hided each item but one. Going to preview the surveypro was still spanning over three pages
-> replaced (and this is a focal point) userdate with date for date, datetime, recurrence, shortdate and time items
-> changed from static to standard two methods that were always called after their class was instanced
> Fixed a bug in time like item

- classes/itembase.php
- field/age/db/upgrade.php
- field/autofill/db/upgrade.php
- field/boolean/db/upgrade.php
- field/character/db/upgrade.php
- field/checkbox/db/upgrade.php
- field/date/db/upgrade.php
- field/datetime/db/upgrade.php
- field/fileupload/db/upgrade.php
- field/integer/db/upgrade.php
- field/multiselect/classes/item.php
- field/multiselect/db/upgrade.php
- field/multiselect/version.php
- field/numeric/db/upgrade.php
- field/radiobutton/db/upgrade.php
- field/rate/db/upgrade.php
- field/recurrence/db/upgrade.php
- field/select/db/upgrade.php
- field/shortdate/db/upgrade.php
- field/textarea/db/upgrade.php
- field/time/db/upgrade.php
- format/fieldset/db/upgrade.php
- format/fieldsetend/db/upgrade.php
- format/label/db/upgrade.php
- format/pagebreak/db/upgrade.php
The issue, IMHO, is here since the very first release of surveypro.
Asking for the list of items (as teacher or admin, of course) the red dot icon allow the user to mark the item (the question corresponding to the item) as mandatory or not.
Of course, if the default of the item is "No answer", that item can NOT be set to mandatory. (if it is mandatory you can not answer: "I don't answer"!)
The user is supposed to change the default to a different value and ONLY AFTER he is allowed to set the item to mandatory.
Asking for the list of items, items type = 'multiselect' were equipped with the possibility to change them to mandatory or not mandatory WITHOUT CARE to the default. This was due to the routine "item_canbemandatory" in itembase.php that was not taking care of the way some item are …
> Fixed wrong default for surveyprofield_multiselect

- field/numeric/classes/item.php
Once a number is localized (for instance 3.14 changed to 3,14) (float) type casting can't be used, of course.
> Deleted (float) from localized numbers

- field/checkbox/classes/item.php
- field/radiobutton/classes/item.php
Now vertical radio button with the option "other" and the field "specify" close the option "other" are correctly displayed. The "specify" field had a distance from the corresponding button proportional to the indent. Now this is no longer true.
In the frame of this PR I also copied the same solution (for the distance between checkbox and the "specify" field) to the checkbox item that was affected by the same problem.
> Modified separators definition

- field/rate/classes/item.php
- field/rate/tests/behat/submit_rate.feature
Changed the appearance of rate type questions from:
to:
when the indent is different from zero.
> Applied hack to align noanswer checkbox in rate item

- classes/submissions_form.php
- classes/submissions_list.php
- classes/utility_submission.php
Actually get_groupmates method from classes/utility_submission.php
never uses the param $cm so I removed it.
```
/**
* surveypro_groupmates
*
-     * @param object $cm
* @param int $userid Optional $userid: the user you want to know his/her groupmates
* @return Array with the list of groupmates of the user
*/
-    public function get_groupmates($cm, $userid=0) {
+    public function get_groupmates($userid=0) {
```
> Removed unused $cm in get_groupmates

- field/rate/classes/item.php
This is the PR about the workaround to pass css styles to surveypro rates mform element.
> Used group workaround to pass css style to rates

- version.php
This release of moodle works in MOODLE_400_STABLE and MOODLE_401_STABLE too. Because of this I have to set the version to 4.0 and not 4.1 otherwise people may think that this release is not working in MOODLE_400_STABLE.
> Changed the release according to supporting moodle version

- classes/itembase.php
- field/radiobutton/classes/item.php
- field/radiobutton/tests/behat/two_option_test.feature
- field/radiobutton/tests/fixtures/usertemplate/mum_or_dad_test.xml
- tests/separator_test.php
Radio button questions with only two options are, in my mind, boolean questions.
This is not true in the mind of some teacher using surveypro.
If you create a surveypro with a radiobutton item with the simple question: Who do you love the most? with:
-  "Choose..." at the beginning (default = invitation);
- mandatory;
- with only two options: "mum" and "dad"
surveypro crashes.
This PR fixes this issue due to wrong definition of the separator between item elements.
> Added a routine to get separator m402

- classes/itembase.php
- field/radiobutton/classes/item.php
- field/radiobutton/tests/behat/two_option_test.feature
- field/radiobutton/tests/fixtures/usertemplate/mum_or_dad_test.xml
- tests/separator_test.php
Radio button questions with only two options are, in my mind, boolean questions.
This is not true in the mind of some teacher using surveypro.
If you create a surveypro with a radiobutton item with the simple question: Who do you love the most? with:
-  "Choose..." at the beginning (default = invitation);
- mandatory;
- with only two options: "mum" and "dad"
surveypro crashes.
This PR fixes this issue due to wrong definition of the separator between item elements.
> Added a routine to get separator master

- field/numeric/classes/item.php
- field/numeric/classes/itemsetupform.php
This PR fixes two errors regarding numeric sub-plugin.
Crate an item type numeric providing, for instance, a lowerbound.
Edit the item and try to wipe the lowerbound. It is not deleted.
Going to fill a form providing 0,0 (in italian) as number the number is wrongly classified as not a number.
> fixed number validation master

- field/numeric/classes/item.php
- field/numeric/classes/itemsetupform.php
This PR fixes two errors regarding numeric sub-plugin.
Create an item type numeric providing, for instance, a lowerbound.
Edit the item and try to wipe the lowerbound. It is not deleted.
Going to fill a form providing 0,0 (in italian) as number the number is wrongly classified as not a number.
> fixed number validation m402

- field/checkbox/classes/item.php
- field/radiobutton/classes/item.php
For consistency with what was done for radiobutton type items, I added the userform_get_separator method to checkbox type items, too. Unlike what I did for radiobutton items, however, I cannot add a unit test here because it would fail. The error is described in the  comment of the method itself.
This PR should be cherry-picked to MOODLE_401_STABLE, MOODLE_402_STABLE and MOODLE_403_STABLE.
> Added userform_get_separator to checkboxes too (master)

- tools.php
With this change the use of the toggle button "Edit mode" (using the theme "boost") restarted to work for the tools page too. The strange behaviour of the missing (or repeated) breadcrumb element "tool" (using the theme "classic") is still alive.
> Replaced require_login with require_course_login

- backup/moodle2/restore_surveypro_activity_task.class.php
- lib.php
Using theme classic the navigation between pages of the module (Surveypro, Layout, Reports, Tools, uTemplate and mTemplate) are driven by the navigation menu. In that menu the link for Reports, uTemplate and mTemplate are wrong.
> Modified wrong links

- classes/utility_page.php
Even if 'section' is quite always needed, it is not required while 's' or 'id' are, FOR SURE. required.
> changed condition in manage_editbutton

- classes/reportbase.php
- classes/submissions_form.php
- layout.php
- mtemplates.php
- report/attachments/classes/report.php
- report/attachments/view.php
- report/colles/view.php
- report/frequency/view.php
- report/lateusers/view.php
- report/responsesperuser/view.php
- report/userspercount/view.php
- reports.php
- tools.php
- utemplates.php
- view.php
This branch has been built on top of wrong_condition_in_manage_editbutton to let it pass GHA.
In the frame of this fix I also:
- verified the presence of "Blocks editing on" in each page (it was missing from report pages)
- moved set_additionalparams close to the other set_* methods in classes/reportbase.php
- reordered methods in a report/attachments/classes/report.php
This PR needs wrong_condition_in_manage_editbutton to work properly.
It should be merged to MOODLE_401|402|403_STABLE too.
> Unified the acquisition of $edit at the beginning of the file

- .github/workflows/moodle-ci.yml
That way we can detect any problem with the supported versions for a given Moodle branch.
Let's see if 401_STABLE passes with both php74 and php81 (the min and max PHP versions supported for that branch)
> Run the tests with both the highest and the lowers PHP versions (401)
