kordan/moodle-mod_surveypro

- field/fileupload/classes/filemanager.php
- field/textarea/classes/editor.php
- locallib.php
1) Registration must point to the real new classes you've created.
2) Every class needs a "constructor" with the name of the class.
> NOBUG: Small missing points for getting the custom elements working.

- classes/itembase.class.php
- classes/itemlist.class.php
- classes/mtemplate.class.php
- classes/templatebase.class.php
- classes/utemplate.class.php
- classes/view_import.class.php
- classes/view_manage.class.php
- classes/view_userform.class.php
- field/age/classes/plugin.class.php
- field/boolean/classes/plugin.class.php
- field/character/classes/plugin.class.php
- field/character/form/plugin_form.php
- field/checkbox/classes/plugin.class.php
- field/date/classes/plugin.class.php
- field/datetime/classes/plugin.class.php
- field/fileupload/classes/plugin.class.php
- field/integer/classes/plugin.class.php
- field/multiselect/classes/plugin.class.php
- field/numeric/classes/plugin.class.php
- field/radiobutton/classes/plugin.class.php
- field/rate/classes/plugin.class.php
- field/recurrence/classes/plugin.class.php
- field/select/classes/plugin.class.php
- field/shortdate/classes/plugin.class.php
- field/textarea/classes/plugin.class.php
- field/time/classes/plugin.class.php
- locallib.php
- report/colles/classes/report.class.php
- view.php
I started the loooooong process of compliance with coding style.
Nothing should be changed in the code execution.
> NOBUG surveypro: shortened some code for compliancy with coding rules

- locallib.php
According to our discussion I added the check of correctness of $type and $plugin in the frame of the surveypro_get_item function
> NOBUG mod_surveypro: added extra checks to surveypro_get_item

- classes/itembase.class.php
- documentation.txt
- field/age/tests/behat/submit_age.feature
- field/character/tests/behat/settings_configuration_01.feature
- field/character/tests/behat/settings_configuration_02.feature
- field/character/tests/behat/settings_configuration_03.feature
- field/character/tests/behat/settings_configuration_04.feature
- field/character/tests/behat/settings_configuration_05.feature
- field/character/tests/behat/settings_configuration_06.feature
- field/character/tests/behat/settings_configuration_07.feature
- field/checkbox/tests/behat/settings_configuration_01.feature
- field/checkbox/tests/behat/settings_configuration_02.feature
- field/checkbox/tests/behat/settings_configuration_03.feature
- field/checkbox/tests/behat/settings_configuration_04.feature
- field/multiselect/tests/behat/settings_configuration_01.feature
- field/multiselect/tests/behat/settings_configuration_02.feature
- field/multiselect/tests/behat/settings_configuration_03.feature
- field/multiselect/tests/behat/settings_configuration_04.feature
- state_of_art_20151115.txt
- tests/behat/backup_restore.feature
- tests/behat/lib_behattest.php
- tests/behat/submission_test.feature
Added new behat test to verify backup and restore.
> NOBUG mod_surveypro: added backup_restore.feature and minor issues

- styles.css
Silly issue with css.
In layout_preview, indented elements were not indented.
> NOBUG mod_surveypro: indent were not applied in preview

- classes/itembase.class.php
RAdio button in item_setup form were not getting the default.
> Item setup form missing defaults

- classes/event/all_items_deleted.php
- classes/utemplate.class.php
- form/utemplates/apply_form.php
- lang/en/surveypro.php
- utemplates_apply.php
first step of the process to introduce bulk action in the right place as agreed in PR #40 and in the [tracker] (https://tracker.moodle.org/browse/CONTRIB-6165)
> CONTRIB-6168 mod_surveypro: removed "none" option

- styles.css
silly changes only affecting style.css
> CONTRIB-6229 mod_surveypro: elements are better v-centred in their row

- field/age/classes/plugin.class.php
- field/autofill/classes/plugin.class.php
- field/character/classes/plugin.class.php
- field/date/classes/plugin.class.php
- field/datetime/classes/plugin.class.php
- field/recurrence/classes/plugin.class.php
- field/shortdate/classes/plugin.class.php
- field/time/classes/plugin.class.php
Finally, at the sixth git commit --amend; git push origin remove_fromvariablenames --force;
all tests executed locally were fine!
With this fix, I am starting to have some chance to see the travis-ci report less red.
I am super satisfied for this!
> CONTRIB-6233 mod_surveypro: removed '_' from property names

- adminlib.php
- classes/itemlist.class.php
Excluding: */yui/build/*, */tests/fixtures/*, */TODO.txt, */documentation.txt, */state_of_art_20151115.txt
finally ZERO errors from codechecker
finally ZERO errors from codechecker
finally ZERO errors from codechecker
finally ZERO errors from codechecker
finally ZERO errors from codechecker
finally ZERO errors from codechecker
not sure if I wrote that...
finally ZERO errors from codechecker
> NOBUG mod_surveypro: finally ZERO errors from codechecker

- classes/view_submissions.class.php
- view_import.php
In the frame of this correction I al so changed the way an import error is detected.
As far as I know, this should be not a sensible change.
> CONTRIB-6239 mod_surveypro: added a vital missed detail

- tests/generator/lib.php
- tests/generator_test.php
- tests/setup_test.php
Minor tweaks to the generator and commented out the
apply_mastertemplate() until we implement it.
> NOBUG: First unitests added

- tests/generator/lib.php
I found that with the merge of c5b98c3
behat test were no longer working fine.
I made a
git co c5b98c3
git diff 23d88bd > local_file_on_my_desktop.txt
and I found that two library were no longer called.
This PR to add them ance again.
NOT SURE AT ALL THIS IS A GOOD PRACTICE.
> CONTRIB-6252 mod_surveypro: required 2 library

- classes/formbase.class.php
- classes/itemlist.class.php
- classes/view_form.class.php
- classes/view_submissions.class.php
- form/outform/fill_form.php
- form/outform/search_form.php
- lib.php
- report/attachments_overview/form/filter_form.php
This is the first time I touch the power of git.
Checking the code, getting branch id from git logs, I found that the error was introduced a long time ago making "code simpler".
This opens to two different thoughts:
1) the module is actually not used, with the exception of me and Andrea (Can I drop backward compatibility)
2) for the first time I have to say thanks to git.
> CONTRIB-6278 mod_surveypro: added a flag to include hidden items too

- classes/event/all_usertemplates_viewed.php
- classes/event/mastertemplate_applied.php
- classes/event/mastertemplate_saved.php
- classes/event/usertemplate_applied.php
- classes/event/usertemplate_deleted.php
- classes/event/usertemplate_exported.php
- classes/event/usertemplate_imported.php
- classes/event/usertemplate_saved.php
- classes/itemlist.class.php
- classes/mtemplate.class.php
- classes/tabs.class.php
- classes/utemplate.class.php
- classes/view_cover.class.php
- classes/view_export.class.php
- classes/view_import.class.php
- db/access.php
- lang/en/surveypro.php
- lang/it/surveypro.php
- layout_manage.php
- mtemplate_apply.php
- mtemplate_save.php
- settings.php
- styles.css
- utemplate_apply.php
- utemplate_import.php
- utemplate_manage.php
- utemplate_save.php
- version.php
- view_export.php
Strings cleanup and file names homogeneity should be welcome
> CONTRIB-6357 mod_surveypro: string and file names cleanup

- classes/tabs.class.php
- classes/utils.class.php
- lib.php
"tab tree" and "admin block" are supposed to display elements according to the action the user is performing. What is supposed to being displayed is a decision that should be taken at central level and not separately for tab tree and for admin block. This branch introduces the central level point to take decisions.
> CONTRIB-6360 mod_surveypro: centralized the decision maker

- classes/itembase.class.php
- classes/view_form.class.php
Submitting a survey with items that are mandatory BUT HIDDEN TOO
the user receive a message ('Some mandatory answer of this response has not been found...') notifying that some mandatory answer was not provided.
Of course, this can't be correct.
> CONTRIB-6373 mod_surveypro: changed sql to select mandatory elements

- classes/mform_utils.php
- field/age/classes/class.php
- field/boolean/classes/class.php
- field/checkbox/mform/advcheckbox.php
- field/checkbox/mform/checkbox.php
- field/fileupload/classes/class.php
- field/fileupload/mform/fileupload.php
- field/radiobutton/classes/class.php
- field/radiobutton/mform/radiobutton.php
- field/rate/classes/class.php
- field/select/mform/select.php
- field/textarea/classes/class.php
- field/textarea/mform/textarea.php
- form/outform/fill_form.php
- form/outform/search_form.php
- format/label/classes/class.php
- format/label/mform/label.php
- layout_preview.php
- lib.php
- locallib.php
- view_form.php
- view_search.php
In the frame of this issue I also added the new class file for mform with the static method to load each element mform class extension
> Special mformclasses dir

- classes/utility.php
- db/upgrade.php
- tests/fixtures/fixsvgcompatability.php
- version.php
I changed the name of the attachment_overview report to attachment
Now I have to uninstall the old report as it is declared "missing from the disk" in the moodle notification page.
> NOBUG mod_surveypro: unistalled old plugin

- lang/it/surveypro.php
- report/attachments/lang/it/surveyproreport_attachments.php
- report/attachments/uploads.php
I also added few Italian string to prove to friends that the translation was not buggy.
> CONTRIB-6403 mod_surveypro: changed $url in $PAGE->set_url($url);

- field/boolean/classes/field.php
- field/checkbox/classes/field.php
- field/date/classes/field.php
- field/datetime/classes/field.php
- field/multiselect/classes/field.php
- field/radiobutton/classes/field.php
- field/rate/classes/field.php
- field/recurrence/classes/field.php
- field/select/classes/field.php
- field/shortdate/classes/field.php
- field/time/classes/field.php
public function item_get_downloadformats() { has typos in some plugin.
This gives empty download format drop down menu in elements setup form.
> CONTRIB-6410 mod_surveypro: fixed typo in item_get_downloadformats

- classes/usertemplate.php
Fixed a typo in the name of a file
> NOBUG mod_surveypro: fixed typo in file name

- classes/utility.php
> NOBUG mod_surveypro: changed incorrect var name

- field/age/classes/field.php
- field/date/classes/field.php
- field/datetime/classes/field.php
- field/recurrence/classes/field.php
- field/shortdate/classes/field.php
- field/time/classes/field.php
editing an item, settings already provided are not remembered.
> CONTRIB-6416 mod_surveypro: fixed names in item_custom_fields_to_form

- adminlib.php
- classes/mastertemplate.php
- classes/templatebase.php
- classes/usertemplate.php
- db/upgrade.php
- tests/fixtures/fixsvgcompatability.php
At usertemplate save time, the plugin version reported in the xml is wrong.
> CONTRIB-6411 mod_surveypro: fixed plugin version in XML

- classes/itembase.php
- classes/submission.php
- field/character/classes/field.php
the original reason for this issue is that the admin was alowed to submit a response but was not allowed to "see" it among responses until he was enrolled in the
course
but
I also found that character elemnts should also be searched for substring and this was still not allowed.
> CONTRIB-6417 mod_surveypro: changed get_submission query

- field/time/classes/field.php
- field/time/form/itemsetup_form.php
- field/time/tests/behat/submit_time.feature
> CONTRIB-6419 mod_surveypro: fixed many details for time plugin

- field/shortdate/classes/field.php
- field/shortdate/form/itemsetup_form.php
> ONTRIB-6420 mod_surveypro: fixed many details for shortdate plugin

- field/recurrence/classes/field.php
- field/recurrence/form/itemsetup_form.php
> CONTRIB-6422 mod_surveypro: fixed many details for recurrence plugin

- field/datetime/classes/field.php
- field/datetime/form/itemsetup_form.php
> CONTRIB-6423 mod_surveypro: fixed many details for datetime plugin

- field/date/classes/field.php
- field/date/form/itemsetup_form.php
> CONTRIB-6424 mod_surveypro: fixed many details for date plugin

- field/age/classes/field.php
- field/age/form/itemsetup_form.php
- field/age/tests/behat/submit_age.feature
- field/age/tests/behat/use_advanced_elements.feature
- tests/behat/submission_test.feature
> CONTRIB-6427 mod_surveypro: fixed many details for age plugin

- field/textarea/classes/field.php
This fixes the issue described in https://github.com/kordan/moodle-mod_surveypro/pull/140
> CONTRIB-6418 mod_surveypro: made textarea searchable

- field/character/classes/field.php
- field/multiselect/classes/field.php
- field/numeric/classes/field.php
> NOBUG mod_surveypro: cleanup wrong classes name

- classes/itemlist.php
- classes/usertemplate.php
- report/userspercount/classes/report.php
Sorting elements by custom number leads to a mysql error.
> CONTRIB-6437 mod_surveypro: denied sort by customnumber

- field/date/classes/field.php
- field/date/form/itemsetup_form.php
- field/date/tests/behat/itemform.feature
- field/date/tests/behat/submit_date.feature
The test is not currently working because of its line 112. It will start to run correctly as soon as #160 will be merged.
> CONTRIB-6442 mod_surveypro: added itemform.feature to date item

- field/datetime/classes/field.php
- field/datetime/form/itemsetup_form.php
- field/datetime/tests/behat/itemform.feature
The test is not currently working because of its line 136. It will start to run correctly as soon as #160 will be merged.
> CONTRIB-6444 mod_surveypro: added itemform.feature to datetime item

- field/recurrence/classes/field.php
- field/recurrence/form/itemsetup_form.php
- field/recurrence/tests/behat/itemform.feature
The test is not currently working because of its line 92. It will start to run correctly as soon as #160 will be merged.
> CONTRIB-6446 mod_surve ypro: added itemform.feature to recurrence item

- field/shortdate/classes/field.php
- field/shortdate/form/itemsetup_form.php
- field/shortdate/tests/behat/itemform.feature
The test is not currently working because of its line 102. It will start to run correctly as soon as #160 will be merged.
> CONTRIB-6447 mod_surve ypro: added itemform.feature to shortdate item

- field/time/classes/field.php
- field/time/form/itemsetup_form.php
- field/time/tests/behat/itemform.feature
The test is not currently working because of its line 99. It will start to run correctly as soon as #160 will be merged.
> CONTRIB-6448 mod_surve ypro: added itemform.feature to time item

- field/datetime/classes/field.php
> NOBUG mod_surveypro: rewritten missing line

- styles.css
I didn't know this could be an issue but...
this is what I found:
styles.css
1: warning at line 102, col 1
Rule doesn't have all its properties in alphabetical order.
styles.css
2: warning at line 125, col 1
Rule doesn't have all its properties in alphabetical order.
styles.css
3: warning at line 132, col 1
Rule doesn't have all its properties in alphabetical order.
styles.css
4: warning at line 162, col 1
Rule doesn't have all its properties in alphabetical order.
styles.css
5: warning at line 229, col 1
Rule doesn't have all its properties in alphabetical order.
styles.css
6: warning at line 238, col 1
Rule doesn't have all its properties in alphabetical order.
styles.css
7: warning at line 244, col 1
Rule doesn't have all its properties in alphabetical order.
styles.css
8: warning at …
> NOBUG mod_surveypro: sorted properties

- field/character/form/itemsetup_form.php
- field/character/lang/en/surveyprofield_character.php
- field/character/tests/behat/itemform.feature
One more test added without discovering hidden issues.
> CONTRIB-6454 mod_surveypro: added itemform.feature to character item

- field/autofill/classes/field.php
- field/autofill/form/itemsetup_form.php
- field/autofill/tests/behat/itemform.feature
- field/autofill/tests/behat/submit_autofill.feature
- tests/behat/preserve_autofillpersonaldata.feature
- tests/behat/submission_test.feature
As usual, introducing new tests, I discovered hidden issues!!!!
Nice that I was the first to get their evidence.
> CONTRIB-6452 mod_surveypro: added itemform.feature to autofill item

- field/boolean/tests/behat/itemform.feature
Finally a test added without discovering hidden issues.
> CONTRIB-6453 mod_surveypro: added itemform.feature to boolean item

- classes/itembase.php
- field/fileupload/db/install.xml
- field/fileupload/db/upgrade.php
- field/fileupload/form/itemsetup_form.php
- field/fileupload/lang/en/surveyprofield_fileupload.php
- field/fileupload/tests/behat/itemform.feature
- field/fileupload/version.php
This was really a battle. I had even forgotten a field in the database.
With this test all seems to be fine now. :)
> CONTRIB-6456 mod_surveypro: added itemform.feature to fileupload item

- field/integer/db/install.xml
- field/integer/db/upgrade.php
- field/integer/tests/behat/itemform.feature
- field/integer/version.php
This was a battle too. I forget the same field in the database here too.
With this test all seems to be fine now. :)
> CONTRIB-6457 mod_surveypro: added itemform.feature to integer item

- field/rate/classes/field.php
- field/rate/form/itemsetup_form.php
- field/rate/lang/en/surveyprofield_rate.php
- field/rate/tests/behat/itemform.feature
- field/rate/version.php
Take care: this test will never run fine until the #178 is merged because of a required method.
> CONTRIB-6463 mod_surveypro: added itemform.feature to rate item

- field/character/tests/behat/trim.feature
- field/textarea/classes/field.php
- field/textarea/mform/textarea_editor.php
- field/textarea/mform/textarea_plain.php
- field/textarea/tests/behat/trim.feature
here I added a test to verify that character and textarea plugins really trim the content when required.
In the frame of this issue I found that simple textareas were displaying frozen fields in a bad way. This is why I added one more class to handle textareas not using editors.
> CONTRIB-6433 mod_surveypro: added trim test

- field/age/tests/behat/itemform.feature
- field/autofill/tests/behat/itemform.feature
- field/boolean/tests/behat/itemform.feature
- field/character/tests/behat/itemform.feature
- field/checkbox/tests/behat/itemform.feature
- field/date/tests/behat/itemform.feature
- field/datetime/tests/behat/itemform.feature
- field/fileupload/tests/behat/itemform.feature
- field/integer/tests/behat/itemform.feature
- field/multiselect/tests/behat/itemform.feature
- field/numeric/tests/behat/itemform.feature
- field/radiobutton/tests/behat/itemform.feature
- field/rate/tests/behat/itemform.feature
- field/recurrence/tests/behat/itemform.feature
- field/select/tests/behat/itemform.feature
- field/shortdate/tests/behat/itemform.feature
- field/textarea/tests/behat/itemform.feature
- field/time/tests/behat/itemform.feature
simply separated two words bad written and copied a lot of times
> NOBUG mod_surveypro: "returnback" to "return back"

- field/textarea/tests/behat/itemform.feature
This PR is even simpler than the previous! 👍
> NOBUG mod_surveypro: deleted temporary tag

- classes/event/item_deleted.php
- classes/event/item_hidden.php
- classes/event/item_shown.php
- classes/itembase.php
- classes/itemlist.php
- classes/mastertemplate.php
- classes/submission.php
- classes/tabs.php
- classes/usertemplate.php
- db/access.php
- layout_items.php
- layout_itemsetup.php
- lib.php
- styles.css
I simply changed a couple of names to more appropriate ones.
The file name "layout_manage.php" changed to "layout_items.php"
> NOBUG mod_surveypro: changed names to more coherent ones

- field/checkbox/tests/behat/itemform.feature
- field/checkbox/tests/behat/settings_configuration_01.feature
- field/checkbox/tests/behat/settings_configuration_02.feature
- field/checkbox/tests/behat/settings_configuration_03.feature
- field/checkbox/tests/behat/settings_configuration_04.feature
- field/multiselect/tests/behat/itemform.feature
- field/multiselect/tests/behat/settings_configuration_01.feature
- field/multiselect/tests/behat/settings_configuration_02.feature
- field/multiselect/tests/behat/settings_configuration_03.feature
- field/multiselect/tests/behat/settings_configuration_04.feature
- field/radiobutton/tests/behat/itemform.feature
- field/radiobutton/tests/behat/submit_radiobutton.feature
- field/rate/tests/behat/itemform.feature
- field/rate/tests/behat/submit_rate.feature
- field/select/tests/behat/itemform.feature
- field/select/tests/behat/submit_select.feature
- field/textarea/tests/behat/itemform.feature
- locallib.php
- tests/behat/behat_mod_surveypro.php
- tests/behat/submission_test.feature
I assume MDL-55329 already merged.
> CONTRIB-6467 surveypro: changed behat functions and corresponding code

- report/frequency/form/item_form.php
- report/frequency/lang/en/surveyproreport_frequency.php
- report/frequency/view.php
As silly as time consuming. I tried all possible incredible solutions before landing to the obvious solution.
> CONTRIB-6477 mod_surveypro: moved $mform->display();

- classes/submission.php
as discussed,
JOIN {role_assignments}
has been replaced by 
JOIN ('.$enrolsql.')
> CONTRIB-6479 mod_surveypro: changed role_assignments to $enrolsql

- classes/view_form.php
as discussed,
JOIN {role_assignments}
has been replaced by
JOIN ('.$enrolsql.')
in mod_surveypro_view_form->notifypeople
> CONTRIB-6480 mod_surveypro: changed role_assignments to $enrolsql

- field/multiselect/tests/behat/itemform.feature
- field/rate/tests/behat/itemform.feature
- field/rate/tests/behat/submit_rate.feature
- tests/behat/submission_test.feature
Silly error. Sorry. 100% my fault.
> NOBUG mod_surveypro: changed Options to Rates

- classes/submission.php
- classes/utility.php
- classes/view_cover.php
- view.php
in the frame of this patch I also replaced $_GET as described in CONTRIB-6483
> CONTRIB-6484 mod_surveypro: deleted useless get_roles_used_in_context

- classes/reportbase.php
- report/attachments/classes/report.php
- report/attachments/view.php
- report/delayedusers/classes/report.php
- report/delayedusers/form/groupfilter_form.php
- report/delayedusers/view.php
If a surveypro activity is divided into groups
reports should provide a jumper between groups
in order to facilitate the access to information.
I am sorry, I was not able to add this new feature without changing the code into attachment too.
It was supposed to be over but I was forced to change the chain of calls. I apologize.
> CONTRIB-6486 mod_surveypro: added jumper to delayedusers report'

- classes/itembase.php
- classes/reportbase.php
- classes/submission.php
- classes/utility.php
- classes/view_form.php
- classes/view_import.php
- field/fileupload/lib.php
- report/attachments/classes/form.php
- report/attachments/classes/report.php
- report/attachments/form/attachmentfilter_form.php
- report/attachments/view.php
- report/colles/classes/report.php
- report/delayedusers/classes/report.php
- report/delayedusers/form/groupfilter_form.php
- report/delayedusers/view.php
Minor not relevant corrections here and there into the same verified queries.
> NOBUG mod_surveypro: correct order of tables in JOIN

- classes/itembase.php
- classes/reportbase.php
- classes/submission.php
- classes/utility.php
- classes/view_form.php
- classes/view_import.php
- field/fileupload/lib.php
- report/attachments/classes/form.php
- report/attachments/classes/report.php
- report/attachments/form/attachmentfilter_form.php
- report/attachments/view.php
- report/colles/classes/report.php
- report/delayedusers/classes/report.php
- report/delayedusers/form/groupfilter_form.php
- report/delayedusers/view.php
- report/frequency/classes/report.php
- report/frequency/form/filter_form.php
- report/frequency/graph.php
- report/frequency/view.php
This branch was created on top of #211 because uses the new parent class structure defined there.
> CONTRIB-6487 mod_surveypro: added jumper to frequency report

- classes/itembase.php
- classes/reportbase.php
- classes/submission.php
- classes/utility.php
- classes/view_form.php
- classes/view_import.php
- field/fileupload/lib.php
- report/attachments/classes/form.php
- report/attachments/classes/report.php
- report/attachments/form/attachmentfilter_form.php
- report/attachments/view.php
- report/colles/classes/report.php
- report/delayedusers/classes/report.php
- report/delayedusers/form/groupfilter_form.php
- report/delayedusers/view.php
- report/frequency/classes/report.php
- report/frequency/form/filter_form.php
- report/frequency/graph.php
- report/frequency/view.php
- report/responsesperuser/classes/report.php
- report/responsesperuser/form/groupfilter_form.php
- report/responsesperuser/view.php
This patch was build on top of #211
> CONTRIB-6488 mod_surveypro: added jumper to responsesperuser report

- field/age/tests/behat/itemform.feature
- field/autofill/tests/behat/itemform.feature
- field/boolean/tests/behat/itemform.feature
- field/character/tests/behat/itemform.feature
- field/character/tests/behat/trim.feature
- field/checkbox/tests/behat/itemform.feature
- field/date/tests/behat/itemform.feature
- field/datetime/tests/behat/itemform.feature
- field/fileupload/tests/behat/itemform.feature
- field/integer/tests/behat/itemform.feature
- field/multiselect/tests/behat/itemform.feature
- field/numeric/tests/behat/itemform.feature
- field/radiobutton/tests/behat/itemform.feature
- field/rate/tests/behat/itemform.feature
- field/recurrence/tests/behat/itemform.feature
- field/select/tests/behat/itemform.feature
- field/shortdate/tests/behat/itemform.feature
- field/textarea/tests/behat/itemform.feature
- field/textarea/tests/behat/trim.feature
- field/time/tests/behat/itemform.feature
I simply changed scenarios to make them different
> NOBUG mod_surveypro: diversified scenario names

- field/integer/tests/behat/itemform.feature
- field/radiobutton/tests/behat/itemform.feature
- field/rate/tests/behat/itemform.feature
- field/select/tests/behat/itemform.feature
Fixed the itemform.feature test of the rate plugin.
> NOBUG mod_surveypro: fixed rate itemform.feature

- field/rate/tests/behat/submit_rate.feature
Fixed the submit_rate.feature test of the rate plugin.
> NOBUG mod_surveypro: fixed rate submit_rate.feature

- report/attachments/view.php
- report/colles/classes/report.php
- report/colles/form/groupfilter_form.php
- report/colles/graph.php
- report/colles/view.php
- report/delayedusers/classes/report.php
- report/delayedusers/view.php
- report/frequency/classes/report.php
- report/frequency/view.php
- report/responsesperuser/classes/report.php
- report/responsesperuser/view.php
- report/userspercount/classes/report.php
- report/userspercount/view.php
If a surveypro activity is divided into groups
reports should provide a jumper between groups
in order to facilitate the access to information.
Here I added this jumper to colles report.
> CONTRIB-6495 mod_surveypro: added jumper to colles report

- classes/reportbase.php
- classes/submission.php
- report/attachments/form/groupfilter_form.php
- report/delayedusers/form/groupfilter_form.php
- report/frequency/classes/report.php
- report/frequency/form/filter_form.php
- report/responsesperuser/form/groupfilter_form.php
- report/responsesperuser/lang/en/surveyproreport_responsesperuser.php
- report/userspercount/form/groupfilter_form.php
- tests/behat/behat_mod_surveypro.php
- tests/fixtures/fixsvgcompatability.php
Silenced few complains of phpdoc checker
> NOBUG mod_surveypro: fixed few phpdoc details

- field/date/classes/field.php
- field/datetime/classes/field.php
- field/time/classes/field.php
> NOBUG mod_surveypro: silenced codechecker complains

- lib.php
When and instance of surveypro is deleted from the corresponding action menu in the course, an error stops the process.
This is due to two variables with the same name.
In the frame of this issue I also cleaned up all the the surveypro_delete_instance function.
> CONTRIB-6518 mod_surveypro: changed repeated variable name

- classes/usertemplate.php
- classes/view_form.php
- field/radiobutton/classes/field.php
- field/select/classes/field.php
The last condition in 
public function userform_child_item_allowed_dynamic($childparentvalue, $data)
of /checkbox/classes/field.php
and of
of /checkbox/select/field.php
was silly bugged. GRRRRRR
I used this issue to make some cleanup and improvements.
> CONTRIB-6519 surveypro: wrong cnd. userform_child_item_allowed_dynamic

- classes/usertemplate.php
Here I simply changed the direction of the arrow in the export icon of the usertemplate list page.
> NOBUG mod_surveypro: changed export to import icon

- classes/view_form.php
- field/numeric/classes/field.php
By submitting a surveypro with "0" in a numeric field, an error stops the submission showing: "This is not a number".
> CONTRIB-6527 mod_surveypro: added ===

- locallib.php
Create a multiselect item.
Provide options but not defaults.
Go to preview.
The first item is selected by default.
> CONTRIB-6528 mod_surveypro: enforced condition

- field/checkbox/classes/field.php
if the student answer to a checkbox element selecting the "No answer" checkbox, the answer is not properly saved to database.
> CONTRIB-6532 mod_surveypro: new code to handle SURVEYPRO_NOANSWERVALUE

- field/select/classes/field.php
Looking at the same method for the integer plugin, I found that this code was longer without any good reason. I reduced it according to the corresponding one in the integer plugin.
> NOBUG mod_surveypro: tiny code cleanup

- field/age/classes/field.php
- field/autofill/classes/field.php
- field/boolean/classes/field.php
- field/character/classes/field.php
- field/checkbox/classes/field.php
- field/date/classes/field.php
- field/datetime/classes/field.php
- field/fileupload/classes/field.php
- field/integer/classes/field.php
- field/multiselect/classes/field.php
- field/numeric/classes/field.php
- field/radiobutton/classes/field.php
- field/rate/classes/field.php
- field/recurrence/classes/field.php
- field/select/classes/field.php
- field/shortdate/classes/field.php
- field/textarea/classes/field.php
- field/time/classes/field.php
I only changed
public function userform_save_preprocessing($answer, $olduseranswer, $searchform) {
to
public function userform_save_preprocessing($answer, &$olduseranswer, $searchform) {
to better see that I am passing $olduseranswer by ref and better understand why I only change $olduseranswer->content returning nothing.
> NOBUG mod_surveypro: specified the pass by ref parameter

- classes/view_form.php
- view_form.php
I simply replaced
firstpage(right|left)
with
nextpage\1
as I better understand what this variable is for.
> NOBUG mod_surveypro: changed firstpage(right|left) to nextpage\1

- tests/behat/parent_boolean.feature
This branch has been created on top of #242 because it needs it to correctly run.
> CONTRIB-6539 mod_surveypro: added parent_boolean test

- tests/behat/parent_select.feature
This branch has been created on top of #242 because it needs it to correctly run.
> CONTRIB-6540 mod_surveypro: added parent_select test

- field/checkbox/classes/field.php
Create a multipage surveypro.
Put a non mandatory checkbox element in the first page and something else in the second one.
Go to fill the surveypro.
Leave each checkbox of the element in the first page unselected and push the `Next page >>` button.
Return to the first page with `<< Previous page` and look at the checkbox element.
No answer is selected by mistake.
> CONTRIB-6542 mod_surveypro: enforced if condition

- classes/submission.php
It was longer to receive that to change!
> CONTRIB-6549 mod_surveypro: changed condition to display

- tests/behat/parent_checkbox.feature
This branch needs #249 to run properly.
> CONTRIB-6551 mod_surveypro: added parent_checkbox test

- tests/behat/parent_select.feature
simply increased what the new test verify
> NOBUG mod_surveypro: improved parentselect test

- tests/behat/parent_boolean.feature
simply increased what the new test verify
> NOBUG mod_surveypro: improved parentboolean test

- classes/itemlist.php
> CONTRIB-6543 mod_surveypro: code cleanup in relation table

- tests/behat/parent_multiselect.feature
This PR needs MDL-56127 merged to work fine.
> CONTRIB-6558 mod_surveypro: added parent_multiselect

- tests/behat/parent_boolean.feature
I simply reduced the number of steps preserving the number of test
> NOBUG mod_surveypro: improved parent_boolean test

- tests/behat/activity_deletion.feature
added a simple test to verify activity deletion
> NOBUG mod_surveypro: tested activity deletion

- field/numeric/classes/field.php
I tried to drop out the "!strlen" but here this is not possible!
> NOBUG mod_surveypro: simplified numeric validation

- classes/view_export.php
I only made a small cleanup to open the way to the bigger change according to: https://github.com/kordan/moodle-mod_surveypro/pull/258#issuecomment-250435061
> NOBUG mod_surveypro: comments only

- classes/itembase.php
Step number 1 to arrive to better manage data saved to database.
> NOBUG mod_surveypro: grouped methods about items

- field/character/classes/field.php
character must save empty string and not null when empty strings are submitted
> CONTRIB-6575 mod_surveypro: fixed char save_preprocessing

- db/upgrade.php
- version.php
Exporting and re-importing data, old code stored '@@_ANINDB_@@' in the database but this was an error. Those records must be deleted and no longer created.
Progresses in the code are in previous PR's. AFAIK this is the closing step.
> CONTRIB-6579 mod_surveypro: deleted dirty answers from db

- field/checkbox/lang/en/surveyprofield_checkbox.php
- field/radiobutton/lang/en/surveyprofield_radiobutton.php
- field/rate/lang/en/surveyprofield_rate.php
- field/select/lang/en/surveyprofield_select.php
Fixed a typo.
Credits to https://github.com/germanvaleroelizondo.
> NOBUG mod_surveypro: fixed typo

- classes/view_export.php
At data export time, attachments must be left out.
The data export process is intended to export data to a software to make statistics and attachments are not supposed to be include.
Moreover even if the export is executed to reimport data in a different surveypro, it is explained inthe import page that files are not handled.
> CONTRIB-6570 mod_surveypro: excluded attachements

- classes/itembase.php
- classes/view_export.php
- classes/view_import.php
- field/textarea/classes/field.php
In https://github.com/kordan/moodle-mod_surveypro/pull/288 contentformat was fixed at save time.
Content format is now correctly handled at export time.
> CONTRIB-6588 mod_surveypro: new contentformat management at export time

- adminlib.php
- backup/moodle2/restore_surveypro_activity_task.class.php
- classes/formbase.php
- classes/itemlist.php
- classes/view_import.php
- field/numeric/classes/field.php
- field/rate/backup/moodle2/restore_surveyprofield_rate_subplugin.class.php
- lib.php
- report/attachments/classes/report.php
- tests/fixtures/fixsvgcompatability.php
- tests/generator/lib.php
> NOBUG mod_surveypro: minor detais

- lang/en/surveypro.php
According to https://github.com/kordan/moodle-mod_surveypro/issues/282
I changed one help string.
Credits to German Valero.
> NOBUG mod_surbeypro: changed help sting

- classes/formbase.php
- classes/itembase.php
- classes/view_form.php
- field/textarea/classes/field.php
- view_form.php
> NOBUG mod_surveypro: only comments were changed

- tests/behat/parent_boolean.feature
- tests/behat/parent_checkbox.feature
- tests/behat/parent_integer.feature
- tests/behat/parent_multiselect.feature
- tests/behat/parent_radiobutton.feature
- tests/behat/parent_select.feature
I found the behat steps:
Then the "ELEMENT_STRING" "FIELD" should be enabled
and
Then the "ELEMENT_STRING" "FIELD" should be disabled
that are shorter than the steps I created for the same purpose, 
so I replaced mine.
> NOBUG mod_surveypro: should only concern not relevant aspects

- db/upgradelib.php
Although I strongly believe the code is correct I have to say that I HAVE NEVER TESTED IT.
How could I test it?
See https://github.com/kordan/moodle-mod_surveypro/issues/299 to get the issue.
Well, to be 100% honest, I tested it in http://sqlfiddle.com/#!15/58a79/9 but... maybe it is not enough.
> CONTRIB-6617 mod_surveypro: modified query

- classes/view_import.php
Importing csv file I got 
Undefined offset: 0 in /Applications/MAMP/htdocs/moodle31/mod/surveypro/classes/view_import.php on line 801
> CONTRIB-6622 mod_surveypro: added test to check array elements are set

- classes/reportbase.php
- classes/view_export.php
- report/attachments/view.php
- report/colles/view.php
- report/delayedusers/view.php
- report/frequency/view.php
- report/responsesperuser/view.php
- report/userspercount/classes/report.php
- report/userspercount/view.php
The query in public function get_submissions_sql() of /report/userspercount/classes/report.php groups by s.userid but doesn't asks ONLY for aggregated data
> CONTRIB-6627 mod_surveypro: rewritten query

- classes/itembase.php
- classes/submission.php
The query in public function get_submissions_sql() of /classes/submission.php groups by s.submissionid but doesn't asks ONLY for aggregated data
> CONTRIB-6631 mod_surveypro: query 100% rewritten

- classes/itembase.php
- classes/submission.php
This branch was created on top of main_get_submissions_sql
because make use of the query newly written there.
> CONTRIB-6634 mod_surveypro: added submission table max size

- report/responsesperuser/classes/report.php
- report/responsesperuser/view.php
Go to a course divided into groups.
Go to a surveypro with some submissions.
Ask for responsesperuser report.
Select a group different from "All groups".
You will see a list of users.
Filter them with a name in the alphabet.
The group menu returns to "All groups"
> CONTRIB-6637 mod_surveypro: added $groupfilterform->set_data

- report/userspercount/view.php
This is not a bug at all.
I made this PR in order to make the code of this report uniform with code of the other reports.
Not any functionality was affected.
> NOBUG mod_surveypro: make the code uniform

- classes/utility.php
Setting an item to mandatory from the green button in the item list page leads to an error.
> CONTRIB-6732 mod_surveypro: fixed the corresponding query

- field/date/classes/field.php
Create a surveypro with a date element.
The search can be performed only using the date field. It can't be ignored.
> CONTRIB-6736 mod_surveypro: revision of date userform_mform_element

- field/recurrence/classes/field.php
Create a surveypro with a recurrence element.
The search can be performed only using the recurrence field. It can't be ignored.
> CONTRIB-6739 surveypro: revision of recurrence userform_mform_element

- field/time/classes/field.php
Create a surveypro with a time element.
The search can be performed only using the time field. It can't be ignored.
> CONTRIB-6741 mod_surveypro: revision of time userform_mform_element

- report/frequency/view.php
Try to run a frequency report with a surveypro in a course not divided into groups.
> CONTRIB-6745 mod_surveypro: protected $groupid

- classes/tabs.php
- classes/utility.php
- field/age/tests/behat/itemform.feature
- field/autofill/tests/behat/itemform.feature
- field/boolean/tests/behat/itemform.feature
- field/character/tests/behat/itemform.feature
- field/checkbox/tests/behat/itemform.feature
- field/date/tests/behat/itemform.feature
- field/datetime/tests/behat/itemform.feature
- field/fileupload/tests/behat/itemform.feature
- field/integer/tests/behat/itemform.feature
- field/multiselect/tests/behat/itemform.feature
- field/numeric/tests/behat/itemform.feature
- field/radiobutton/tests/behat/itemform.feature
- field/rate/tests/behat/itemform.feature
- field/recurrence/tests/behat/itemform.feature
- field/select/tests/behat/itemform.feature
- field/shortdate/tests/behat/itemform.feature
- field/textarea/tests/behat/itemform.feature
- field/time/tests/behat/itemform.feature
- lib.php
- tests/behat/navigation.feature
It is silly to have a central method providing permissions for links but not providing urls too.
Yesterday I used this central method to understand if the link was allowed AND THEN I calculated urls in each calling method.
Today I changed the method so if a link is allowed, the related url (calculated at central level) is returned too.
> NOBUG mod_surveypro: centralized urls definition

- form/data/import_form.php
In the form to upload data in csv format, it was needed to force the extension to .csv
> NOBUG mod_surveypro: limited csvfile to .csv

- tests/behat/behat_mod_surveypro.php
dropped last chained step
simpler than expected
> NOBUG mod_surveypro: dropped last chained step

- tests/behat/submission_test.feature
submission_test.feature was one of the first tests I wrote and it tests each item creation with few different configurations. With the time I added a lot more tests testing with more detail each item setup witha lot of different configurations and this test has become uselessly long. This isi why I reduced it to a shorter version.
> NOBUG mod_surveypro: shortened submission_test

- field/checkbox/classes/field.php
- field/multiselect/classes/field.php
Create a surveypro with multiselect item.
Fill it at least one time.
Export to PDF the answer.
The item exported is not correct.
> CONTRIB-6876 mod_surveypro: rewritten db_to_export procedure

- version.php
starting development for moodle 3.2
> NOBUG mod_surveypro: version bump

- field/age/classes/field.php
The same as #346 for MOODLE_31_STABLE
> CONTRIB-6936 mod_surveypro: prefill now includes _noanswer checkbox

- field/shortdate/classes/field.php
The same as #347 for MOODLE_31_STABLE
> CONTRIB-6938 mod_surveypro: prefill now includes _noanswer checkbox

- field/date/classes/field.php
The same as #348 for MOODLE_31_STABLE
> CONTRIB-6939 mod_surveypro: prefill now includes _noanswer checkbox

- field/datetime/classes/field.php
The same as #349 for MOODLE_31_STABLE
> CONTRIB-6940 mod_surveypro: prefill now includes _noanswer checkbox

- field/recurrence/classes/field.php
The same as #350 for MOODLE_31_STABLE
> CONTRIB-6941 mod_surveypro: prefill now includes _noanswer checkbox

- field/time/classes/field.php
The same as #351 for MOODLE_31_STABLE
> CONTRIB-6942 mod_surveypro: prefill now includes _noanswer checkbox

- field/checkbox/classes/field.php
The same as #352 for MOODLE_31_STABLE
> CONTRIB-6935 mod_surveypro: prefill now includes _noanswer checkbox

- tests/behat/activity_deletion.feature
fixed activity_deletion.feature to make it wirking with boost too.
> NOBUG mod_surveypro: fixed activity_deletion.feature to include boost

- tests/behat/thankspage.feature
fixed thankspage.feature to make it working with boost too.
> NOBUG mod_surveypro: fixed thankspage.feature to include boost

- report/attachments/form/groupjumper_form.php
- report/attachments/view.php
- report/colles/form/groupjumper_form.php
- report/colles/view.php
- report/delayedusers/form/groupjumper_form.php
- report/delayedusers/view.php
- report/frequency/form/itemfilter_form.php
- report/frequency/view.php
- report/responsesperuser/form/groupjumper_form.php
- report/responsesperuser/view.php
- report/userspercount/form/groupjumper_form.php
- report/userspercount/view.php
changed the group jumper technology to let it work in moodle 3.3 too. 
YUI has been dropped in favour of jquery.
One questions:
1) why do the class "autosubmit" is still required?
2) should I create a amd/src and amd/build to centralize it?
> NOBUG mod_surveypro: autosubmit for M3.3

- tests/behat/usertemplate_apply.feature
> NOBUG mod_surveypro: behat pause deletion

- styles.css
They were centuries I knew this issue but I never had the right time to look at it.
Today, waiting for behat tests, I finally faced the challenge.
The fix is super silly.
> CONTRIB-7055 mod_surveypro: added one missing style

- styles.css
Added a styles to provide the same space between icons even if they are a surveypro custom icon and moodle core icon.
> NOBUG mod_surveypro: added style to include tag i

- field/age/tests/behat/itemform.feature
- field/autofill/tests/behat/itemform.feature
- field/boolean/tests/behat/itemform.feature
- field/character/tests/behat/itemform.feature
- field/checkbox/tests/behat/itemform.feature
- field/date/tests/behat/itemform.feature
- field/datetime/tests/behat/itemform.feature
- field/fileupload/tests/behat/itemform.feature
- field/integer/tests/behat/itemform.feature
- field/multiselect/tests/behat/itemform.feature
- field/numeric/tests/behat/itemform.feature
- field/radiobutton/tests/behat/itemform.feature
- field/rate/tests/behat/itemform.feature
- field/recurrence/tests/behat/itemform.feature
- field/select/tests/behat/itemform.feature
- field/shortdate/tests/behat/itemform.feature
- field/textarea/tests/behat/itemform.feature
- field/time/tests/behat/itemform.feature
- tests/behat/navigation.feature
- tests/behat/overwrite_mastertemplate.feature
- tests/behat/submission_test.feature
As far as I know I fixed a lot of behat issues at once:
```javascript
003 Scenario: test age setup form # /Applications/MAMP/htdocs/master/mod/surveypro/field/age/tests/behat/itemform.feature:8
And I follow "Preview"      # /Applications/MAMP/htdocs/master/mod/surveypro/field/age/tests/behat/itemform.feature:96
The "(//html/.//a
[./@href][((./@id = 'Preview' or contains(normalize-space(string(.)), 'Preview') or contains(./@title, 'Preview') or contains(./@rel, 'Preview')) or .//*[(contains(concat(' ', @class, ' '), ' icon ') or name() = 'img') and (contains(./@alt, 'Preview') or contains(./@title, 'Preview'))])] | //html/.//*
[translate(./@role, 'ABCDEFGHIJKLMNOPQRSTUVWXYZ', 'abcdefghijklmnopqrstuvwxyz') = 'link'][((./@id = 'Preview' or contains(./@value, 'Preview')) or contains(./@title, …
```
> NOBUG mod_surveypro: specified page link place

- field/age/tests/behat/itemform.feature
- field/character/tests/behat/itemform.feature
- field/checkbox/tests/behat/settings_configuration_01.feature
- field/checkbox/tests/behat/settings_configuration_02.feature
- field/checkbox/tests/behat/settings_configuration_03.feature
- field/checkbox/tests/behat/settings_configuration_04.feature
- field/fileupload/tests/behat/itemform.feature
- field/integer/tests/behat/itemform.feature
- field/integer/tests/behat/submit_integer.feature
- field/multiselect/tests/behat/itemform.feature
- field/multiselect/tests/behat/settings_configuration_02.feature
- field/numeric/tests/behat/submit_numeric.feature
- field/radiobutton/tests/behat/itemform.feature
- field/rate/tests/behat/itemform.feature
- field/select/tests/behat/itemform.feature
- field/select/tests/behat/submit_select.feature
- field/textarea/tests/behat/itemform.feature
- field/textarea/tests/behat/settings_configuration.feature
- format/fieldset/tests/behat/add_fieldset.feature
- format/label/tests/behat/add_label.feature
- tests/behat/parent_checkbox.feature
Just to drop 45 lines of code (hoping it doesn't affect test execution).
> NOBUG mod_surveypro: not relevant replace

- lang/en/surveypro.php
'Surveypro allows the creation of custom surveys and the use of built in surveys ' gives a better description of what this plugin does :)
> Rewrite in a more understandable way

- field/character/classes/field.php
- field/integer/classes/field.php
- field/textarea/classes/field.php
xss were not updated last time I changed the structure of the database for elements.
Actually a simple issue but opening to big problems.
> CONTRIB-7110 mod_surveypro: updates of xss

- field/fileupload/backup/moodle2/backup_surveyprofield_fileupload_subplugin.class.php
- field/fileupload/classes/field.php
- field/integer/backup/moodle2/backup_surveyprofield_integer_subplugin.class.php
- field/integer/classes/field.php
- field/integer/db/install.xml
- field/time/backup/moodle2/backup_surveyprofield_time_subplugin.class.php
- format/fieldsetend/backup/moodle2/backup_surveyproformat_fieldsetend_subplugin.class.php
Few fields have been missed in backup structure during last years upgrades
> NOBUG mod_surveypro: aligned backup to tables structure

- classes/formbase.php
- field/character/classes/field.php
- field/character/form/itemsetup_form.php
- field/character/lang/en/surveyprofield_character.php
- field/character/lang/es_mx/surveyprofield_character.php
- field/character/lib.php
None asked me for this new feature but I had it in my mind since a long time ago.
I was wondering if it was possible to verify the content of a character plugin (short text) field against a regular expression.
This PR is more a proof of strength than a real need.
By the way, it also works fine. It is a satisfaction. :)
> NOBUG mod_surveypro: added regex as custom pattern

- .travis.yml
- db/upgrade.php
- field/character/tests/behat/trim.feature
- field/textarea/tests/behat/itemform.feature
- field/textarea/tests/behat/trim.feature
- report/attachments/styles.css
- report/delayedusers/styles.css
- report/responsesperuser/styles.css
- styles.css
- tests/behat/navigation.feature
- tests/behat/thankspage.feature
This  incorporates various changes in travis and coding style towards completing #403 (work will continue there) . Still there is more work to do, but better we merge these before conflicts arrive.
For your consideration.. ciao :-)
> Travis back (take#1)

- template/attls/lang/es_mx/surveyprotemplate_attls.php
I feel you will not find any difficulty.
> removed gosh w

- classes/view_import.php
An import bug rose up a wrong method call. Fixed both.
> mod_surveypro: wrong opentag changed

- template/attls/template.xml
- template/collesactual/template.xml
- template/collesactualpreferred/template.xml
- template/collespreferred/template.xml
- template/criticalincidents/template.xml
Behat failure verification started.
> updated mtemplates according to #396

- classes/task/cron_task.php
- db/tasks.php
- lang/en/surveypro.php
- lib.php
I added this because it seems that Vlad really need this feature as he wrote in https://github.com/kordan/moodle-mod_surveypro/issues/430.
I still don't know if it really works. I only found that the first test passed here on my local server.
> added cron_tasks

- db/upgradelib.php
- field/boolean/lang/it/surveyprofield_boolean.php
- field/checkbox/lang/it/surveyprofield_checkbox.php
- field/radiobutton/lang/it/surveyprofield_radiobutton.php
- lib.php
very very minor changes to italian language as requested by people of my Institute going to use surveypro for their own needs next week.
> minor italian lang additions

- classes/itembase.php
The rationale of this PR is that I want to change a duplicated name of a variable by adding to it a final _progressivenumber like "_001" or "_002" and so on BUT ONLY IF IT IS NOT already in the format of duplicatename_001. In this case I don't want to change it to duplicatename_001_001 but to duplicatename_002.
> improved varname validation

- db/access.php
- version.php
Site security report said: 'Incorrectly defined frontpage role "" detected!'
> Site secury report fixed

- classes/itembase.php
- classes/itemlist.php
- classes/mastertemplate.php
- classes/templatebase.php
- field/age/classes/field.php
- field/autofill/classes/field.php
- field/boolean/classes/field.php
- field/character/backup/moodle2/backup_surveyprofield_character_subplugin.class.php
- field/character/classes/field.php
- field/character/db/install.xml
- field/checkbox/classes/field.php
- field/date/classes/field.php
- field/datetime/classes/field.php
- field/fileupload/classes/field.php
- field/integer/classes/field.php
- field/multiselect/classes/field.php
- field/numeric/classes/field.php
- field/radiobutton/classes/field.php
- field/rate/classes/field.php
- field/recurrence/classes/field.php
- field/select/classes/field.php
- field/shortdate/classes/field.php
- field/textarea/backup/moodle2/backup_surveyprofield_textarea_subplugin.class.php
- field/textarea/classes/field.php
- field/textarea/db/install.xml
- field/time/classes/field.php
- format/fieldset/classes/format.php
- format/fieldsetend/classes/format.php
- format/label/classes/format.php
- format/pagebreak/classes/format.php
Some multilang fields were missing.
In the frame of this branch I also fixed few minor issues, cleaned the code and renamed some strange named variables.
> added missing fields to mastertemplates

- .travis.yml
- tests/behat/multilang_mastertemplate.feature
There were few minor issues in one of the two jumped tests 
but the main reason is not in this PR as it is out of this context.
It was the missing:
define ('TOOL_LANGIMPORT_REMOTE_TESTS', true);
from my local config.php
> Multilang feature

- classes/view_form.php
- field/age/form/itemsetup_form.php
- field/autofill/form/itemsetup_form.php
- field/boolean/form/itemsetup_form.php
- field/character/form/itemsetup_form.php
- field/checkbox/form/itemsetup_form.php
- field/date/form/itemsetup_form.php
- field/datetime/form/itemsetup_form.php
- field/fileupload/form/itemsetup_form.php
- field/integer/form/itemsetup_form.php
- field/multiselect/form/itemsetup_form.php
- field/numeric/form/itemsetup_form.php
- field/radiobutton/form/itemsetup_form.php
- field/rate/form/itemsetup_form.php
- field/recurrence/form/itemsetup_form.php
- field/select/form/itemsetup_form.php
- field/shortdate/form/itemsetup_form.php
- field/textarea/form/itemsetup_form.php
- field/time/form/itemsetup_form.php
- form/items/itembase_form.php
- format/fieldset/form/itemsetup_form.php
- format/fieldsetend/form/itemsetup_form.php
- format/label/form/itemsetup_form.php
- format/pagebreak/form/itemsetup_form.php
- layout_itemsetup.php
I realized that at each item load I was passing to the editing form the surveypro record twice! 
Forces of nature, forgive me!
Behat exit was:
108 scenari (108 superati)
4471 passaggi (4471 superati)
92m32.17s (37.23Mb)
> waste of memory is never a good option

- field/fileupload/db/install.xml
- field/fileupload/db/upgrade.php
- field/fileupload/version.php
the extensions sometimes may require more than 32 characters. I increased the available space to 64.
> increased size for filetypes

- field/numeric/tests/behat/multiformat.feature
- template/collesactual/tests/behat/graphs.feature
- template/collesactualpreferred/tests/behat/graphs.feature
- template/collespreferred/tests/behat/graphs.feature
- tests/behat/bulk_action.feature
- tests/behat/export_items_count.feature
- tests/behat/item_action.feature
- tests/behat/multilang_mastertemplate.feature
- tests/behat/navigation.feature
- tests/behat/overwrite_mastertemplate.feature
- tests/behat/parent_boolean.feature
- tests/behat/parent_checkbox.feature
- tests/behat/parent_integer.feature
- tests/behat/parent_multiselect.feature
- tests/behat/parent_radiobutton.feature
- tests/behat/parent_select.feature
- tests/behat/restore_simple.feature
- tests/behat/thankspage.feature
- tests/behat/usertemplate_apply.feature
- tests/behat/usertemplate_applyall.feature
- tests/behat/usertemplate_create.feature
Only changes to let behat work fine in master.
> updated behat syntax

- format/fieldset/backup/moodle2/backup_surveyproformat_fieldset_subplugin.class.php
- format/fieldset/classes/format.php
- format/fieldset/db/install.xml
- format/fieldset/db/upgrade.php
- format/fieldset/form/itemsetup_form.php
- format/fieldset/lang/en/surveyproformat_fieldset.php
- format/fieldset/version.php
Now the editing teacher can choose the status of the fieldsets at page load time.
0 => force closed
1 => force opened
2 => follow factory setting (moodle defaults)
> added default state on page load for fieldset

- field/checkbox/classes/field.php
- field/checkbox/lang/it/surveyprofield_checkbox.php
Added misteriously lost routines to the patch that was complete last friday
> Added maximumrequired to checkbox (second step)

- field/textarea/lang/it/surveyprofield_textarea.php
> italian strings for textarea

- template/attls/template.xml
- template/collesactual/template.xml
- template/collesactualpreferred/template.xml
- template/collespreferred/template.xml
- tests/fixtures/usertemplate/MMM_2015123000.xml
- tests/fixtures/usertemplate/checkbox_only_2015123000.xml
- tests/fixtures/usertemplate/item_action_test.xml
- tests/fixtures/usertemplate/multiselect_only_2015123000.xml
- tests/fixtures/usertemplate/parent-child_2015123000.xml
updated user templates according to recent modifications in fieldset, checkbox and multiselect plugins
> upgraded utemplates to last changes

- field/numeric/classes/field.php
- field/numeric/tests/behat/multiformat.feature
In italian, enter a number with two decimals, submit the form and reopen it.
You wrote 12,34
but you get 12.34
and you must correct the number format to submit the form once again.
Fixed.
> fixed an issue with decinal separator

- classes/submission.php
- classes/usertemplate.php
Following your "unrelated comment" to the problem... isn't the download icon incorrect?
> simple change of icon

- classes/privacy/provider.php
This is my proposal.
What really counts is that I HAVE NEVER TESTED it because a test should destroy my db.
When this PR will be merged I will concentrate over the issue with pictures in PDF.
> proposal to include userlist_provider

- classes/itembase.php
- classes/submission.php
Into
public static function userform_standardcontent_to_string($content) {
of 
classes/itembase.php
I found an incredible
if (!isset($content)) { // Item was disabled.
that was, for sure, an issue due to the continous editing of the code.
I studied angain the code and I fixed it.
In the frame of this job I made a code cleanup of the routine sending a response to PDF.
> fixed incompatibility of if(!isset($content

- classes/view_form.php
Situation: you have a conditioned item. 
Item y depends from the answer to item x.
User provides the answer, to item x, that enables the child, y, then fill item y and submit.
User edits his submission and changes the answer to item x making y no longer expected.
User submits.
The previously saved answer to item y has to be deleted.
> dropped, already saved but no longer expected, answers

- classes/itembase.php
- classes/layout.php
- classes/layout_customnumber.php
- classes/layout_insearchform.php
- classes/layout_required.php
- classes/layout_reserved.php
- classes/layout_variable.php
- layout_itemlist.php
- layout_itemsetup.php
- layout_validation.php
changed the name of the set of classes dealing with layout from itemlist* to layout*
> renamed itemlist to layout

- classes/ipe_layout_customnumber.php
- classes/ipe_layout_insearchform.php
- classes/ipe_layout_required.php
- classes/ipe_layout_reserved.php
- classes/ipe_layout_variable.php
- classes/layout.php
- lib.php
> Diversify ipe classes name

- tests/behat/bulk_action.feature
simple change of names
nothing to check
> changed name according to the feature to test

- classes/utility.php
Add an item
Just after, delete it.
A warning is displayed because the item has not related answer.
> changed return of method get_user_from_answersid

- classes/layout.php
- field/age/classes/field.php
- field/autofill/classes/field.php
- field/boolean/classes/field.php
- field/character/classes/field.php
- field/checkbox/classes/field.php
- field/date/classes/field.php
- field/datetime/classes/field.php
- field/fileupload/classes/field.php
- field/integer/classes/field.php
- field/multiselect/classes/field.php
- field/numeric/classes/field.php
- field/radiobutton/classes/field.php
- field/recurrence/classes/field.php
- field/select/classes/field.php
- field/shortdate/classes/field.php
- field/textarea/classes/field.php
- field/time/classes/field.php
Now the user if free to add a picture in the element label and to display it in the form even if the position of the content is on the left of the item.
From now on the user is responsible of what he write in the question content. I no longer drop tags from his input.
The height of the rows in the list of items will be corrected, as it should be, using css.
> Element label is finally written as it is

- adminlib.php
- classes/ipe_layout_variable.php
- classes/itembase.php
- classes/layout.php
- classes/mastertemplate.php
- classes/submission.php
- classes/usertemplate.php
- classes/view_export.php
- classes/view_import.php
- field/character/classes/field.php
- field/character/form/itemsetup_form.php
- field/character/lib.php
- field/checkbox/classes/field.php
- field/fileupload/form/itemsetup_form.php
- field/numeric/classes/field.php
- field/numeric/form/itemsetup_form.php
- field/textarea/classes/field.php
- field/textarea/form/itemsetup_form.php
- field/textarea/mform/textarea_editor.php
- field/textarea/mform/textarea_plain.php
- lib.php
As suggested in #510 
It was 100% new to me.
Super thank you!
> In use now strlen and substr from core_text class

- adminlib.php
- classes/itembase.php
- classes/layout.php
- classes/submission.php
- classes/usertemplate.php
- classes/view_export.php
- field/character/lib.php
- field/checkbox/classes/field.php
- field/numeric/classes/field.php
- field/numeric/form/itemsetup_form.php
- field/textarea/classes/field.php
- field/textarea/form/itemsetup_form.php
- field/textarea/mform/textarea_editor.php
- field/textarea/mform/textarea_plain.php
partial restore of standard strlen and substr in order to save time as suggested in https://github.com/kordan/moodle-mod_surveypro/pull/519/#issuecomment-473954295
> partial restore of standard strlen and substr

- classes/itembase.php
- classes/view_import.php
- field/age/classes/field.php
- field/autofill/classes/field.php
- field/boolean/classes/field.php
- field/character/classes/field.php
- field/checkbox/classes/field.php
- field/date/classes/field.php
- field/datetime/classes/field.php
- field/fileupload/classes/field.php
- field/integer/classes/field.php
- field/multiselect/classes/field.php
- field/numeric/classes/field.php
- field/radiobutton/classes/field.php
- field/rate/classes/field.php
- field/recurrence/classes/field.php
- field/select/classes/field.php
- field/shortdate/classes/field.php
- field/textarea/classes/field.php
- field/time/classes/field.php
- format/fieldset/classes/format.php
- format/fieldsetend/classes/format.php
- format/label/classes/format.php
- format/pagebreak/classes/format.php
> changed a variable name to a more significant one

- classes/layout.php
- styles.css
Added few margin-right to make icon separation uniform in the list of items
> minor aesthetic details

- classes/itembase.php
- format/fieldsetend/classes/format.php
- format/pagebreak/classes/format.php
This should replace #527 that is not correct (and I do not understand why)
> introduced uses_db_table method

- field/numeric/tests/behat/multiformat.feature
- tests/behat/behat_mod_surveypro.php
minor changes to behat method i_follow_in_the_language_menu stored into acrivity personal library
> fine tuning of i_follow_in_the_language_menu

- tests/behat/multilang_mastertemplate.feature
minor changes to be compliant with current required syntax
> minor changes in behat test

- field/checkbox/classes/field.php
- field/checkbox/mform/advcheckbox.php
- field/checkbox/mform/checkbox.php
- field/fileupload/mform/fileupload.php
- field/radiobutton/classes/field.php
- field/radiobutton/mform/radiobutton.php
- field/textarea/mform/textarea_editor.php
- field/textarea/mform/textarea_plain.php
- form/outform/fill_form.php
- state_of_art_20151115.txt
- styles.css
Replaces #531 as it was not satisfing grunt
> summary of changes to get compliancy with boost

- tests/behat/preserve_autofillpersonaldata.feature
now this test no longer fails using boost as theme
> added compliancy with boost too

- field/age/styles.css
- field/autofill/styles.css
- field/checkbox/styles.css
- field/datetime/classes/field.php
- field/datetime/styles.css
- field/radiobutton/styles.css
- field/rate/styles.css
- field/textarea/styles.css
- format/fieldset/styles.css
- format/pagebreak/styles.css
- index.php
- layout_itemsetup.php
- report/attachments/styles.css
- report/delayedusers/styles.css
- report/responsesperuser/styles.css
- styles.css
This is only the first step due to errors that I can not understand where they come from.
I included also the second step dividing styles between field and format elements.
> Partial style restore

- tests/lib_test.php
> changed silly param in data provider

- db/subplugins.json
- db/subplugins.php
In Italy we use to say: "Tagliamo la testa al toro" that literally is: "Let's cut off the bull's head".
The meaning is: don't waste your to time to look for a workaround but go to fix the main issue.
In this context, is: instead to fix alarms for deprecated code, go straight to update the deprecated code and carry on.
> added subplugins.json

- tests/behat/activity_deletion.feature
This fix make the first behat test run once again.
> fix according to new behat syntax

- field/fileupload/tests/behat/submit_attachment.feature
- tests/behat/item_action.feature
- tests/behat/restore_simple.feature
- tests/behat/submission_test.feature
- tests/behat/thankspage.feature
- tests/behat/usertemplate_apply.feature
- tests/behat/usertemplate_applyall.feature
- tests/behat/usertemplate_create.feature
Running behat tests I got:
/Applications/MAMP/htdocs/master/mod/surveypro/tests/behat/item_action.feature:134
And I upload "mod/surveypro/tests/fixtures/usertemplate/item_action_test.xml" file to "Choose files to import" filemanager # /Applications/MAMP/htdocs/master/mod/surveypro/tests/behat/item_action.feature:142
File upload tests must have the @_file_upload tag on either the scenario or feature. (Behat\Mink\Exception\DriverException)
> Added @_file_upload tag on either the scenario or feature

- tests/behat/see_onlypersonalsubmissions.feature
I simply dropped two behat lines of code in order to have test pass
> Behat test minor repair

- classes/itembase.php
- field/age/classes/field.php
- field/autofill/classes/field.php
- field/boolean/classes/field.php
- field/character/classes/field.php
- field/checkbox/classes/field.php
- field/date/classes/field.php
- field/datetime/classes/field.php
- field/fileupload/classes/field.php
- field/integer/classes/field.php
- field/multiselect/classes/field.php
- field/numeric/classes/field.php
- field/radiobutton/classes/field.php
- field/recurrence/classes/field.php
- field/select/classes/field.php
- field/shortdate/classes/field.php
- field/textarea/classes/field.php
- field/time/classes/field.php
The issue comes out because the item content no longer is "This is a question" but maybe "<p>This is a question</p>" or "<p dir='ltr'>This is a question</p>"
> Added a routine to include the item customnumber into the item content

- classes/view_form.php
There was an incredible hole in the code.
Start a two items long surveypro allowing pause/resume.
Go to fill the survetpro. You will see the "Pause" button.
Ignore it at the moment.
Fill each item of the surveypro and save.
Now edit it.
You still see the "Pause" button.
Set the first item to a not correct answer ("Choose an item" of a select, for instance).
Now push the "Pause" button.
The item is saved in the database BUT THE surveypro_submission IS NOT SAVED so the result is that the user answer is "CLOSED" but with a not valid field.
> Added $DB->update_record for surveypro paused too

- field/boolean/tests/behat/customnumebr_inclusion.feature
/Applications/MAMP/htdocs/stable(MOODLE_311_STABLE|…) % vendor/bin/behat --config /Applications/MAMP/data/behat$instance/behatrun/behat/behat.yml --name="include custom numbers into element question/content" 
Moodle 3.11.3+ (Build: 20211026), b8e5f7b428aaf5e97cc6ec9b10df949651b73094
Php: 7.4.2, mysqli: 5.7.26, OS: Darwin 20.6.0 x86_64
Run optional tests:
- Accessibility: No
Server OS "Darwin", Browser: "firefox"
Started at 31-10-2021, 02:00
...................................................................... 70
...................................................................... 140
...................................................................... 210
..............
14 scenari (14 superati)
224 passaggi (224 superati)
5m3.93s (27.64Mb)
> minimal change to .feature

- classes/tabs.php
- layout_itemlist.php
- layout_itemsetup.php
- layout_preview.php
- layout_validation.php
- mtemplate_apply.php
- mtemplate_save.php
- report/attachments/classes/report.php
- report/attachments/uploads.php
- report/attachments/view.php
- report/colles/graph.php
- report/colles/view.php
- report/frequency/graph.php
- report/frequency/view.php
- report/lateusers/classes/report.php
- report/lateusers/view.php
- report/responsesperuser/classes/report.php
- report/responsesperuser/view.php
- report/userspercount/classes/report.php
- report/userspercount/view.php
- utemplate_apply.php
- utemplate_import.php
- utemplate_manage.php
- utemplate_save.php
- view.php
- view_cover.php
- view_export.php
- view_form.php
- view_import.php
- view_search.php
added completion details into module pages
and fixed an issues for report page that were wrongly selected
(yes, I am sorry.)
> added completion details into module pages

- classes/view_form.php
- view_form.php
If the survey is maked as "anonymous" I can not send email saying "Mr. firstname, familyname submitted a response"
> Covered sensible attributes with xxxx

- classes/view_export.php
If I look for "in progress" responses I can not ask for "verified answers" beacuse, of course, if a response is "in progress" it can not have "verified answers".
> Changed selection query

- .github/workflows/moodle-ci.yml
Just that, keep 2 jobs (postgres and mariadb), with 2 PHP versions (max and min for that branch). Both jobs running with master SP and master Moodle.
> Make SP master to only be tested against master Moodle

- classes/reportbase.php
- report/attachments/view.php
- report/colles/view.php
- template/collesactual/tests/behat/reportswithanswers.feature
- template/collesactual/tests/behat/reportswithoutanswers.feature
- tests/behat/preserve_autofillpersonaldata.feature
Groupid get lost from colles/view.php with the time and colles report stopped working.
Maybe this will open to more issue in the future. I do not know at the moment.
> Two more tests

- report/lateusers/classes/report.php
Waiting for behat report to see if the new query is correct for mysql and postgresql too.
> dropped alias

- backup/moodle2/backup_surveypro_stepslib.php
> added completionsubmit to backup stepslib

- template/collesactual/tests/behat/reportswithanswers.feature
- template/collesactual/tests/behat/reportswithoutanswers.feature
- tests/behat/behat_mod_surveypro.php
dropped some commented line
and used "new" jump way to reach report page
tests passed
> semplified code

- report/lateusers/classes/report.php
As far as I know all is correct now.
Can you please check it too just to be sure?
> grouped by surveyproid too

- classes/view_submissions.php
Related behat test will follow.
> Added missing \ here too

- classes/task/mail_neverstarted.php
- classes/task/mail_oneshotmp.php
- classes/task/mail_pauseresume.php
This is why I say: "I am old".
if I get interrupted, I lose the thread and I lose pieces.
This PR is the proof.
> Added forgotten mandatory fields to user record

- tests/behat/duplicate_response.feature
In the past this test went missed. I can not remember when and why and I don't even care those infos. But, in any case, it is better to have it into the code than dropped out.
> Reintroduced lost behat test

- classes/mastertemplate.php
- tests/lib_test.php
- tests/mastertemplate_test.php
> added routine to check mtemplate name

- classes/itembase.php
$utilitylayoutman is defined in line 364 and in line 516. The second definition has been dropped.
> Dropped duplicated $utilitylayoutman definition

- classes/view_form.php
Submitting a surveypro using "Pause" button generates a submission with "creation time" = 0
> Added management of pause submit button

- classes/event/all_submissions_exported.php
- classes/event/item_deleted.php
- classes/event/item_hidden.php
- classes/event/item_shown.php
- classes/event/submissions_imported.php
- classes/itembase.php
- classes/layout_itemsetup.php
- classes/mastertemplate.php
- classes/tools_export.php
- classes/tools_import.php
- classes/usertemplate.php
- classes/utility_layout.php
- db/access.php
- layout_itemsetup.php
- layout_itemslist.php
- tools_export.php
- tools_import.php
I find this step is welcome in the frame of the update of the primary navigation that is going to arrive.
> Renamed some landing pages

- layout_itemsetup.php
- layout_itemslist.php
- layout_preview.php
- layout_validation.php
- mtemplate_apply.php
- mtemplate_save.php
- report/attachments/uploads.php
- report/attachments/view.php
- report/colles/view.php
- report/frequency/view.php
- report/lateusers/view.php
- report/responsesperuser/view.php
- report/userspercount/view.php
- tools_export.php
- tools_import.php
- utemplate_apply.php
- utemplate_import.php
- utemplate_manage.php
- utemplate_save.php
- view.php
- view_form.php
- view_search.php
- view_submissions.php
With moodle4 the button to start and stop editing is no longer needed inside the activity module.
> Removed blocksedit button from landing pages

- classes/view_submissions.php
As workaround of the TCPDF library bug commented in
https://github.com/moodle/moodle/blob/MOODLE_311_STABLE/dataformat/pdf/classes/writer.php#L109
I replaced the direct picture link with the picture encoded file.
> replaced direct link with base64 encoded file (m311)

- adminlib.php
- classes/itembase.php
- classes/layout_itemsetup.php
- classes/local/form/itemsetupbaseform.php
- classes/local/ipe/usertemplate_name.php
- classes/mastertemplate.php
- classes/plugininfo/surveyprofield.php
- classes/plugininfo/surveyproformat.php
- classes/plugininfo/surveyproreport.php
- classes/plugininfo/surveyprotemplate.php
- classes/tools_export.php
- classes/usertemplate.php
- classes/utility_item.php
- classes/view_submissions.php
- field/character/lib.php
- field/checkbox/classes/item.php
- field/numeric/classes/item.php
- field/numeric/classes/itemsetupform.php
- field/textarea/classes/item.php
- field/textarea/classes/itemsetupform.php
- field/textarea/mform/textarea_editor.php
- field/textarea/mform/textarea_plain.php
- format/fieldset/classes/itemsetupform.php
I forget to open this pull request last month with her cousin, too.
This patch clean the name of the file to export gathered data.
If the name of the instance of surveypro was an html link, the name of the file to export gathered data was a mess.
> More compatible file name (master)

- adminlib.php
- classes/itembase.php
- classes/layout_itemsetup.php
- classes/local/form/itemsetupbaseform.php
- classes/local/form/submissionimportform.php
- classes/local/ipe/usertemplate_name.php
- classes/mastertemplate.php
- classes/plugininfo/surveyprofield.php
- classes/plugininfo/surveyproformat.php
- classes/plugininfo/surveyproreport.php
- classes/plugininfo/surveyprotemplate.php
- classes/usertemplate.php
- classes/utility_item.php
- classes/view_export.php
- classes/view_import.php
- classes/view_submissions.php
- field/character/classes/item.php
- field/character/classes/itemsetupform.php
- field/character/lib.php
- field/checkbox/classes/item.php
- field/fileupload/classes/itemsetupform.php
- field/numeric/classes/item.php
- field/numeric/classes/itemsetupform.php
- field/textarea/classes/item.php
- field/textarea/classes/itemsetupform.php
- field/textarea/mform/textarea_editor.php
- field/textarea/mform/textarea_plain.php
- format/fieldset/classes/itemsetupform.php
- lib.php
I forget to open this pull request last month with her cousin, too.
This patch clean the name of the file to export gathered data.
If the name of the instance of surveypro was an html link, the name of the file to export gathered data was a mess.
> More compatible file name (MOODLE_311_STABLE)

- classes/event/all_submissions_exported.php
- classes/event/all_submissions_viewed.php
- classes/event/all_usertemplates_viewed.php
- classes/event/course_module_viewed.php
- classes/event/form_previewed.php
- classes/event/item_created.php
- classes/event/item_deleted.php
- classes/event/item_hidden.php
- classes/event/item_modified.php
- classes/event/item_shown.php
- classes/event/mastertemplate_applied.php
- classes/event/mastertemplate_saved.php
- classes/event/submission_created.php
- classes/event/submission_deleted.php
- classes/event/submission_duplicated.php
- classes/event/submission_modified.php
- classes/event/submission_viewed.php
- classes/event/submissions_imported.php
- classes/event/submissiontopdf_downloaded.php
- classes/event/usertemplate_applied.php
- classes/event/usertemplate_deleted.php
- classes/event/usertemplate_exported.php
- classes/event/usertemplate_imported.php
- classes/event/usertemplate_saved.php
Built on top of #773.
Running tests againsta moodle 4.2 I was requested to drop legacy code from event's classes
> Events minor updates

- .github/workflows/moodle-ci.yml
As from the suggestion of a great moodler, I dropped the installation of node from .github/workflows/moodle-ci.yml
> Useless node installation

- field/age/classes/item.php
- field/date/classes/item.php
- field/datetime/classes/item.php
- field/recurrence/classes/item.php
- field/shortdate/classes/item.php
- field/time/classes/item.php
- report/frequency/classes/filterform.php
This is as siily and short and not relevant at all.
> Only comments

- field/character/tests/behat/settings_configuration_01.feature
- template/collesactual/tests/behat/graphs.feature
- template/collesactualpreferred/tests/behat/graphs.feature
- template/collespreferred/tests/behat/graphs.feature
- tests/behat/behat_mod_surveypro.php
- tests/behat/item_action.feature
- tests/behat/navigation.feature
- tests/behat/overwrite_mastertemplate.feature
- tests/behat/usertemplate_apply.feature
- tests/behat/usertemplate_applyall.feature
- tests/behat/usertemplate_create.feature
I am quite sure the errors found by behat tests are not something related to actions I can afford.
IMHO with this PR:
- provide more homogeneous page resolvers
- the time I am wasting to go, before, to the generic surveypro report page and, after, to the specific report home page is a 100% false prolblem.
Because of this, I am opening this pull request anyway.
> more homogeneous behat steps

- field/character/classes/itemsetupform.php
> Added missing break

- backup/moodle2/restore_surveypro_stepslib.php
- classes/cover.php
- classes/itembase.php
- classes/layout_itemsetup.php
- classes/local/ipe/layout_customnumber.php
- classes/mastertemplate.php
- classes/output/action_bar.php
- classes/submissions_form.php
Sonarqube directed me to these useless assignments (and more are going to arrive)
> removed waste of time and memory

- classes/output/action_bar.php
I simply moved "Preview" as last item of the jump menu. Super trivial.
> Preview is the last item in jump menu

- classes/reportbase.php
- report/attachments/classes/report.php
Added this-> to a not local variable.
> Fixed issue in attachements report

- classes/plugininfo/surveyprofield.php
- classes/plugininfo/surveyproformat.php
- classes/plugininfo/surveyproreport.php
- classes/plugininfo/surveyprotemplate.php
GHA are only at the beginning but I trust that it will all work out fine.
> Changed include to include_once

- version.php
Finally, after 12 years of development and use I found the brave to say "I arrived to a beta release"
> moved to beta version

- classes/local/form/utemplate_createform.php
- utemplates.php
Added a default to the user template name at creation time.
> Added default for utemplate name

- classes/local/form/userform.php
- format/fieldsetend/classes/item.php
Modified a bit the way to garantee the colours alternation in the survey form for the user
> Changed details for colours alternation

- field/age/styles.css
- field/autofill/styles.css
- field/checkbox/styles.css
- field/datetime/styles.css
- field/radiobutton/styles.css
- field/rate/styles.css
- field/textarea/styles.css
- format/fieldset/styles.css
- format/pagebreak/styles.css
- report/attachments/styles.css
- report/lateusers/styles.css
- report/responsesperuser/styles.css
- styles.css
Following the suggestion received in the frame of #794 and after the  intermediate step in branch more_specific_styles_rev2, I try this extreme solution that allow me to simplify a lot styles.css
This PR closes #787
I am still missing the modifications to items css.
I will use this branch for few days. It already seems correct but I want to check it more . 🤞
> Testing never considered ways

- field/checkbox/db/upgrade.php
- field/checkbox/version.php
For the description read the corresponding description of #811 replacing multiselect with checkbox.
> Fixed wrong default for surveyprofield_checkbox

- field/date/classes/item.php
- field/datetime/classes/item.php
- field/recurrence/classes/item.php
- field/shortdate/classes/item.php
- field/time/classes/item.php
I returned to userdate instead of date to avoid the use of embedded formats
> New format in userform_get_filling_instructions

- classes/local/form/userform.php
I dropped the label "Note:" to meke the form less crowded
> dropped the label "Note:"

- classes/local/form/utemplate_createform.php
- classes/submissions_form.php
- field/numeric/tests/behat/multiformat.feature
- lang/it/surveypro.php
- mod_form.php
> Only unrelevant changes

- field/textarea/tests/behat/itemform.feature
- report/attachments/tests/behat/attachment_functionality.feature
It is supposed that this PR will be merged to master ONLY AFTER the release of MOODLE_401_STABLE.
It fixes an issue due to the new editor in m402.
> Changed content editor to textarea

- tests/behat/thankspage.feature
It is supposed that this PR will be merged to master ONLY AFTER the release of MOODLE_401_STABLE.
It fixes the way to upload a picture in m402.
> Changed the way to upload a picture

- classes/itembase.php
- classes/utility_layout.php
I am not sure about the correctness of this code.
If it is correct, it is ready for merge.
> Escaped Exception

- .github/workflows/moodle-ci.yml
- classes/local/ipe/layout_customnumber.php
- classes/local/ipe/layout_insearchform.php
- classes/local/ipe/layout_required.php
- classes/local/ipe/layout_reserved.php
- classes/local/ipe/layout_variable.php
- classes/local/ipe/usertemplate_name.php
- field/fileupload/tests/behat/submit_attachment.feature
- version.php
It is supposed that this PR will be merge to master ONLY AFTER the release of MOODLE_401_STABLE.
It changes the moodle reference version and the required.
> Bump to m402

- field/select/classes/item.php
- template/collesactual/tests/behat/graphs.feature
- template/collesactual/tests/behat/reportswithanswers.feature
- template/collesactual/tests/behat/reportswithoutanswers.feature
- template/collesactualpreferred/tests/behat/graphs.feature
- template/collespreferred/tests/behat/graphs.feature
- tests/behat/change_of_mind.feature
- tests/behat/parent_select.feature
- tests/behat/readonly_browse_allowed_pages_only.feature
- tests/behat/submission_test.feature
This is the PR about the workaround to pass css styles to select mform element.
> Used group workaround to pass css style to select

- field/rate/classes/item.php
This is the PR about the workaround to pass css styles to surveypro rates mform element.
> Used group workaround to pass css style to rates

- field/integer/classes/item.php
- field/integer/tests/behat/submit_integer.feature
- tests/behat/parent_integer.feature
- tests/behat/submission_test.feature
This is the PR about the workaround to pass css styles to surveypro integer mform element.
> Used group workaround to pass css style to integer

- lib.php
I only changed the name of the function
create_event_on_calendar
to
surveypro_create_event_on_calendar
in lib.php
> Changed the name of a function

- view.php
Deleted redundant class instantiation
> Duplicated class instantiation

- report/attachments/classes/form.php
- report/attachments/classes/output/view_report_paragraph.php
- report/attachments/renderer.php
- report/attachments/styles.css
- report/attachments/templates/report_details.mustache
The output of the attachment report was wrong.
It was supposed to reflect the two colums style of moodle mform but it was on a single column since a long time.
> Added a template to the attachment report

- version.php
Increased versione to cache new strings
> new release to cache new strings m402

- version.php
Increased versione to cache new strings
> new release to cache new strings master

- field/checkbox/lang/en/surveyprofield_checkbox.php
- field/checkbox/lang/it/surveyprofield_checkbox.php
- field/multiselect/lang/en/surveyprofield_multiselect.php
- field/radiobutton/lang/en/surveyprofield_radiobutton.php
- field/radiobutton/lang/it/surveyprofield_radiobutton.php
- field/rate/lang/en/surveyprofield_rate.php
- field/select/lang/en/surveyprofield_select.php
- field/select/lang/it/surveyprofield_select.php
This commit should be cherry-picked to MOODLE_403_STABLE, MOODLE_402_STABLE and MOODLE_401_STABLE in addition to the branch master.
> Removed lib from lang files (master)

- classes/output/action_bar.php
This is the reason for this PR.
This PR should be cherry-picked to MOODLE_403_STABLE, MOODLE_402_STABLE and MOODLE_401_STABLE in addition to the branch master.
> Strengthened condition to use of $linktosave (master)

- version.php
> Increased version for master

- README.md
This PR should be cherry-picked to MOODLE_403_STABLE, MOODLE_402_STABLE and MOODLE_401_STABLE in addition to the branch master.
> Better readme.md

- field/character/lang/it/surveyprofield_character.php
- field/numeric/classes/item.php
This string was esplicitally requested as vital!
I hope it will never be responsible of the end of the world. 😡
> One more it string (master)

- field/character/lang/it/surveyprofield_character.php
- field/numeric/classes/item.php
This string was esplicitally requested as vital!
I hope it will never be responsible of the end of the world. 😡
> One more it string (m401)

- field/character/lang/it/surveyprofield_character.php
This string was esplicitally requested as vital!
I hope it will never be responsible of the end of the world. 😡
> One more it string (m402)

- field/character/lang/it/surveyprofield_character.php
- field/numeric/classes/item.php
This string was esplicitally requested as vital!
I hope it will never be responsible of the end of the world. 😡
> One more it string (m403)

- report/attachments/view.php
- report/colles/view.php
- report/frequency/view.php
- report/lateusers/view.php
- report/responsesperuser/view.php
- report/userspercount/view.php
As far as I know nothing should be added or removed by this PR. Added only blank lines or reordered sets of a few recurring lines in different files.
> Added homogeneity only

- classes/surveypro_file_info.php
- lib.php
- version.php
In order to allow users with capability 'moodle/course:managefiles' to select, for instance, pictures already uploaded to the server in the frame of the definition of the content of some item I added the class surveypro_file_info and I called it form the function surveypro_get_file_info of lib.php
I am finally satisfied of the code.
> Added class surveypro_file_info to sPro for m403

- classes/surveypro_file_info.php
- lib.php
- version.php
In order to allow users with capability 'moodle/course:managefiles' to select, for instance, pictures already uploaded to the server in the frame of the definition of the content of some item I added the class surveypro_file_info and I called it form the function surveypro_get_file_info of lib.php
I am finally satisfied of the code.
> Added class surveypro_file_info to sPro for m402

- classes/surveypro_file_info.php
- lib.php
- version.php
In order to allow users with capability 'moodle/course:managefiles' to select, for instance, pictures already uploaded to the server in the frame of the definition of the content of some item I added the class surveypro_file_info and I called it form the function surveypro_get_file_info of lib.php
I am finally satisfied of the code.
> Added class surveypro_file_info to sPro for m401

- layout.php
- mtemplates.php
- report/attachments/view.php
- report/colles/graph.php
- report/colles/view.php
- report/frequency/view.php
- report/lateusers/view.php
- report/responsesperuser/view.php
- report/userspercount/view.php
- reports.php
- tools.php
- utemplates.php
- view.php
> small code modernization

- classes/submissions_list.php
Please merge this PR to MOODLE_m401|m402|m403_STABLE too. Thanks.
> Added DISTINCT to submission id too.

- classes/submissions_list.php
Please cherry-pick this to (m401|m402|m403) too.
> Polish vowels

- classes/itembase.php
- field/age/classes/item.php
- field/autofill/classes/item.php
- field/boolean/classes/item.php
- field/character/classes/item.php
- field/checkbox/classes/item.php
- field/date/classes/item.php
- field/datetime/classes/item.php
- field/fileupload/classes/item.php
- field/integer/classes/item.php
- field/multiselect/classes/item.php
- field/numeric/classes/item.php
- field/radiobutton/classes/item.php
- field/rate/classes/item.php
- field/recurrence/classes/item.php
- field/select/classes/item.php
- field/shortdate/classes/item.php
- field/textarea/classes/item.php
- field/time/classes/item.php
- format/label/classes/item.php
I can not remember why this property is here and I can not imagine what it was used for. Searching for it in the code I found it is never used. I try to delete it.
master only
> Deleted contenttrust

- lib.php
> Same FEATURE_MOD_PURPOSE as data activity module

- classes/layout_itemsetup.php
I removed a bunch of lines of code because I already copied them to the setup form of the same class.
> Removed duplicated code

- field/checkbox/db/install.xml
- field/multiselect/db/install.xml
Resolves #965 on MOODLE_403_STABLE branch.
> Fix database schema after #811 and #812

- field/shortdate/lang/it/surveyprofield_shortdate.php
Nothing more than few more italian strings as requested by users of a work team. Version for surveypro branch MOODLE_405_STABLE
> Few more italian strings
